/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
  CommentFromJSON,
  CommentFromJSONTyped,
  CommentToJSON,
  CommentToJSONTyped,
} from './Comment';

/**
 *
 * @export
 * @interface CommentList
 */
export interface CommentList {
  /**
   *
   * @type {Array<Comment>}
   * @memberof CommentList
   */
  data: Array<Comment>;
  /**
   *
   * @type {string}
   * @memberof CommentList
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof CommentList
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the CommentList interface.
 */
export function instanceOfCommentList(value: object): value is CommentList {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function CommentListFromJSON(json: any): CommentList {
  return CommentListFromJSONTyped(json, false);
}

export function CommentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentList {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(CommentFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function CommentListToJSON(json: any): CommentList {
  return CommentListToJSONTyped(json, false);
}

export function CommentListToJSONTyped(
  value?: CommentList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(CommentToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
