/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateComment
 */
export interface CreateComment {
  /**
   *
   * @type {string}
   * @memberof CreateComment
   */
  content: string;
}

/**
 * Check if a given object implements the CreateComment interface.
 */
export function instanceOfCreateComment(value: object): value is CreateComment {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function CreateCommentFromJSON(json: any): CreateComment {
  return CreateCommentFromJSONTyped(json, false);
}

export function CreateCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateComment {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
  };
}

export function CreateCommentToJSON(json: any): CreateComment {
  return CreateCommentToJSONTyped(json, false);
}

export function CreateCommentToJSONTyped(
  value?: CreateComment | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
  };
}
