/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateReviewByMeeting
 */
export interface CreateReviewByMeeting {
  /**
   *
   * @type {number}
   * @memberof CreateReviewByMeeting
   */
  score: number;
  /**
   *
   * @type {string}
   * @memberof CreateReviewByMeeting
   */
  comment: string;
}

/**
 * Check if a given object implements the CreateReviewByMeeting interface.
 */
export function instanceOfCreateReviewByMeeting(value: object): value is CreateReviewByMeeting {
  if (!('score' in value) || value['score'] === undefined) return false;
  if (!('comment' in value) || value['comment'] === undefined) return false;
  return true;
}

export function CreateReviewByMeetingFromJSON(json: any): CreateReviewByMeeting {
  return CreateReviewByMeetingFromJSONTyped(json, false);
}

export function CreateReviewByMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateReviewByMeeting {
  if (json == null) {
    return json;
  }
  return {
    score: json['score'],
    comment: json['comment'],
  };
}

export function CreateReviewByMeetingToJSON(json: any): CreateReviewByMeeting {
  return CreateReviewByMeetingToJSONTyped(json, false);
}

export function CreateReviewByMeetingToJSONTyped(
  value?: CreateReviewByMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    score: value['score'],
    comment: value['comment'],
  };
}
