/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateMeeting
 */
export interface CreateMeeting {
  /**
   *
   * @type {string}
   * @memberof CreateMeeting
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateMeeting
   */
  type: string;
  /**
   * 카카오맵 주소에서 추출한 시/도 + 구/군 (예: '서울 강남구', '경기 성남시 분당구')
   * @type {string}
   * @memberof CreateMeeting
   */
  region: string;
  /**
   * 카카오맵 장소명 + 도로명주소 + 상세주소 (쉼표 구분)
   * @type {string}
   * @memberof CreateMeeting
   */
  address?: string;
  /**
   * 카카오맵에서 반환된 위도
   * @type {number}
   * @memberof CreateMeeting
   */
  latitude?: number;
  /**
   * 카카오맵에서 반환된 경도
   * @type {number}
   * @memberof CreateMeeting
   */
  longitude?: number;
  /**
   *
   * @type {Date}
   * @memberof CreateMeeting
   */
  dateTime: Date;
  /**
   *
   * @type {Date}
   * @memberof CreateMeeting
   */
  registrationEnd: Date;
  /**
   *
   * @type {number}
   * @memberof CreateMeeting
   */
  capacity: number;
  /**
   *
   * @type {string}
   * @memberof CreateMeeting
   */
  image?: string;
  /**
   *
   * @type {string}
   * @memberof CreateMeeting
   */
  description?: string;
}

/**
 * Check if a given object implements the CreateMeeting interface.
 */
export function instanceOfCreateMeeting(value: object): value is CreateMeeting {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('region' in value) || value['region'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  if (!('registrationEnd' in value) || value['registrationEnd'] === undefined) return false;
  if (!('capacity' in value) || value['capacity'] === undefined) return false;
  return true;
}

export function CreateMeetingFromJSON(json: any): CreateMeeting {
  return CreateMeetingFromJSONTyped(json, false);
}

export function CreateMeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMeeting {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    type: json['type'],
    region: json['region'],
    address: json['address'] == null ? undefined : json['address'],
    latitude: json['latitude'] == null ? undefined : json['latitude'],
    longitude: json['longitude'] == null ? undefined : json['longitude'],
    dateTime: new Date(json['dateTime']),
    registrationEnd: new Date(json['registrationEnd']),
    capacity: json['capacity'],
    image: json['image'] == null ? undefined : json['image'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function CreateMeetingToJSON(json: any): CreateMeeting {
  return CreateMeetingToJSONTyped(json, false);
}

export function CreateMeetingToJSONTyped(
  value?: CreateMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    type: value['type'],
    region: value['region'],
    address: value['address'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    dateTime: value['dateTime'].toISOString(),
    registrationEnd: value['registrationEnd'].toISOString(),
    capacity: value['capacity'],
    image: value['image'],
    description: value['description'],
  };
}
