/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreatePost
 */
export interface CreatePost {
  /**
   *
   * @type {string}
   * @memberof CreatePost
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof CreatePost
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof CreatePost
   */
  image?: string;
}

/**
 * Check if a given object implements the CreatePost interface.
 */
export function instanceOfCreatePost(value: object): value is CreatePost {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function CreatePostFromJSON(json: any): CreatePost {
  return CreatePostFromJSONTyped(json, false);
}

export function CreatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePost {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    content: json['content'],
    image: json['image'] == null ? undefined : json['image'],
  };
}

export function CreatePostToJSON(json: any): CreatePost {
  return CreatePostToJSONTyped(json, false);
}

export function CreatePostToJSONTyped(
  value?: CreatePost | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    content: value['content'],
    image: value['image'],
  };
}
