/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FavoriteCount
 */
export interface FavoriteCount {
  /**
   *
   * @type {number}
   * @memberof FavoriteCount
   */
  count: number;
}

/**
 * Check if a given object implements the FavoriteCount interface.
 */
export function instanceOfFavoriteCount(value: object): value is FavoriteCount {
  if (!('count' in value) || value['count'] === undefined) return false;
  return true;
}

export function FavoriteCountFromJSON(json: any): FavoriteCount {
  return FavoriteCountFromJSONTyped(json, false);
}

export function FavoriteCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteCount {
  if (json == null) {
    return json;
  }
  return {
    count: json['count'],
  };
}

export function FavoriteCountToJSON(json: any): FavoriteCount {
  return FavoriteCountToJSONTyped(json, false);
}

export function FavoriteCountToJSONTyped(
  value?: FavoriteCount | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value['count'],
  };
}
