/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JoinedMeeting } from './JoinedMeeting';
import {
  JoinedMeetingFromJSON,
  JoinedMeetingFromJSONTyped,
  JoinedMeetingToJSON,
  JoinedMeetingToJSONTyped,
} from './JoinedMeeting';

/**
 *
 * @export
 * @interface JoinedMeetingList
 */
export interface JoinedMeetingList {
  /**
   *
   * @type {Array<JoinedMeeting>}
   * @memberof JoinedMeetingList
   */
  data: Array<JoinedMeeting>;
  /**
   *
   * @type {string}
   * @memberof JoinedMeetingList
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof JoinedMeetingList
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the JoinedMeetingList interface.
 */
export function instanceOfJoinedMeetingList(value: object): value is JoinedMeetingList {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function JoinedMeetingListFromJSON(json: any): JoinedMeetingList {
  return JoinedMeetingListFromJSONTyped(json, false);
}

export function JoinedMeetingListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): JoinedMeetingList {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(JoinedMeetingFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function JoinedMeetingListToJSON(json: any): JoinedMeetingList {
  return JoinedMeetingListToJSONTyped(json, false);
}

export function JoinedMeetingListToJSONTyped(
  value?: JoinedMeetingList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(JoinedMeetingToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
