/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MeetingType
 */
export interface MeetingType {
  /**
   *
   * @type {number}
   * @memberof MeetingType
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof MeetingType
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof MeetingType
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof MeetingType
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof MeetingType
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the MeetingType interface.
 */
export function instanceOfMeetingType(value: object): value is MeetingType {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function MeetingTypeFromJSON(json: any): MeetingType {
  return MeetingTypeFromJSONTyped(json, false);
}

export function MeetingTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingType {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    name: json['name'],
    description: json['description'],
    createdAt: new Date(json['createdAt']),
  };
}

export function MeetingTypeToJSON(json: any): MeetingType {
  return MeetingTypeToJSONTyped(json, false);
}

export function MeetingTypeToJSONTyped(
  value?: MeetingType | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    name: value['name'],
    description: value['description'],
    createdAt: value['createdAt'].toISOString(),
  };
}
