/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationData } from './NotificationData';
import {
  NotificationDataFromJSON,
  NotificationDataFromJSONTyped,
  NotificationDataToJSON,
  NotificationDataToJSONTyped,
} from './NotificationData';

/**
 *
 * @export
 * @interface Notification
 */
export interface Notification {
  /**
   *
   * @type {number}
   * @memberof Notification
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof Notification
   */
  userId: number;
  /**
   *
   * @type {NotificationTypeEnum}
   * @memberof Notification
   */
  type: NotificationTypeEnum;
  /**
   *
   * @type {string}
   * @memberof Notification
   */
  message: string;
  /**
   *
   * @type {NotificationData}
   * @memberof Notification
   */
  data: NotificationData;
  /**
   *
   * @type {boolean}
   * @memberof Notification
   */
  isRead: boolean;
  /**
   *
   * @type {Date}
   * @memberof Notification
   */
  createdAt: Date;
}

/**
 * @export
 */
export const NotificationTypeEnum = {
  MeetingConfirmed: 'MEETING_CONFIRMED',
  MeetingCanceled: 'MEETING_CANCELED',
  MeetingDeleted: 'MEETING_DELETED',
  Comment: 'COMMENT',
} as const;
export type NotificationTypeEnum = (typeof NotificationTypeEnum)[keyof typeof NotificationTypeEnum];

/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('isRead' in value) || value['isRead'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function NotificationFromJSON(json: any): Notification {
  return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    userId: json['userId'],
    type: json['type'],
    message: json['message'],
    data: NotificationDataFromJSON(json['data']),
    isRead: json['isRead'],
    createdAt: new Date(json['createdAt']),
  };
}

export function NotificationToJSON(json: any): Notification {
  return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(
  value?: Notification | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    userId: value['userId'],
    type: value['type'],
    message: value['message'],
    data: NotificationDataToJSON(value['data']),
    isRead: value['isRead'],
    createdAt: value['createdAt'].toISOString(),
  };
}
