/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParticipantUser } from './ParticipantUser';
import {
  ParticipantUserFromJSON,
  ParticipantUserFromJSONTyped,
  ParticipantUserToJSON,
  ParticipantUserToJSONTyped,
} from './ParticipantUser';

/**
 *
 * @export
 * @interface Participant
 */
export interface Participant {
  /**
   *
   * @type {number}
   * @memberof Participant
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Participant
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof Participant
   */
  meetingId: number;
  /**
   *
   * @type {number}
   * @memberof Participant
   */
  userId: number;
  /**
   *
   * @type {Date}
   * @memberof Participant
   */
  joinedAt: Date;
  /**
   *
   * @type {ParticipantUser}
   * @memberof Participant
   */
  user?: ParticipantUser;
}

/**
 * Check if a given object implements the Participant interface.
 */
export function instanceOfParticipant(value: object): value is Participant {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('meetingId' in value) || value['meetingId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
  return true;
}

export function ParticipantFromJSON(json: any): Participant {
  return ParticipantFromJSONTyped(json, false);
}

export function ParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Participant {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    meetingId: json['meetingId'],
    userId: json['userId'],
    joinedAt: new Date(json['joinedAt']),
    user: json['user'] == null ? undefined : ParticipantUserFromJSON(json['user']),
  };
}

export function ParticipantToJSON(json: any): Participant {
  return ParticipantToJSONTyped(json, false);
}

export function ParticipantToJSONTyped(
  value?: Participant | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    meetingId: value['meetingId'],
    userId: value['userId'],
    joinedAt: value['joinedAt'].toISOString(),
    user: ParticipantUserToJSON(value['user']),
  };
}
