/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Post
 */
export interface Post {
  /**
   *
   * @type {number}
   * @memberof Post
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof Post
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof Post
   */
  authorId: number;
  /**
   *
   * @type {number}
   * @memberof Post
   */
  viewCount: number;
  /**
   *
   * @type {number}
   * @memberof Post
   */
  likeCount: number;
  /**
   *
   * @type {Date}
   * @memberof Post
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Post
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Post interface.
 */
export function instanceOfPost(value: object): value is Post {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
  if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function PostFromJSON(json: any): Post {
  return PostFromJSONTyped(json, false);
}

export function PostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Post {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    title: json['title'],
    content: json['content'],
    image: json['image'],
    authorId: json['authorId'],
    viewCount: json['viewCount'],
    likeCount: json['likeCount'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function PostToJSON(json: any): Post {
  return PostToJSONTyped(json, false);
}

export function PostToJSONTyped(value?: Post | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    title: value['title'],
    content: value['content'],
    image: value['image'],
    authorId: value['authorId'],
    viewCount: value['viewCount'],
    likeCount: value['likeCount'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
