/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostWithCommentsAllOfAuthor
 */
export interface PostWithCommentsAllOfAuthor {
  /**
   *
   * @type {number}
   * @memberof PostWithCommentsAllOfAuthor
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostWithCommentsAllOfAuthor
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof PostWithCommentsAllOfAuthor
   */
  image: string;
  /**
   *
   * @type {string}
   * @memberof PostWithCommentsAllOfAuthor
   */
  email: string;
}

/**
 * Check if a given object implements the PostWithCommentsAllOfAuthor interface.
 */
export function instanceOfPostWithCommentsAllOfAuthor(
  value: object
): value is PostWithCommentsAllOfAuthor {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  return true;
}

export function PostWithCommentsAllOfAuthorFromJSON(json: any): PostWithCommentsAllOfAuthor {
  return PostWithCommentsAllOfAuthorFromJSONTyped(json, false);
}

export function PostWithCommentsAllOfAuthorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostWithCommentsAllOfAuthor {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    image: json['image'],
    email: json['email'],
  };
}

export function PostWithCommentsAllOfAuthorToJSON(json: any): PostWithCommentsAllOfAuthor {
  return PostWithCommentsAllOfAuthorToJSONTyped(json, false);
}

export function PostWithCommentsAllOfAuthorToJSONTyped(
  value?: PostWithCommentsAllOfAuthor | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    image: value['image'],
    email: value['email'],
  };
}
