/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PresignedUrlResponse
 */
export interface PresignedUrlResponse {
  /**
   * S3 presigned PUT URL (5분 유효)
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  presignedUrl: string;
  /**
   * 업로드 완료 후 접근 가능한 공개 URL
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  publicUrl: string;
}

/**
 * Check if a given object implements the PresignedUrlResponse interface.
 */
export function instanceOfPresignedUrlResponse(value: object): value is PresignedUrlResponse {
  if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
  if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
  return true;
}

export function PresignedUrlResponseFromJSON(json: any): PresignedUrlResponse {
  return PresignedUrlResponseFromJSONTyped(json, false);
}

export function PresignedUrlResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PresignedUrlResponse {
  if (json == null) {
    return json;
  }
  return {
    presignedUrl: json['presignedUrl'],
    publicUrl: json['publicUrl'],
  };
}

export function PresignedUrlResponseToJSON(json: any): PresignedUrlResponse {
  return PresignedUrlResponseToJSONTyped(json, false);
}

export function PresignedUrlResponseToJSONTyped(
  value?: PresignedUrlResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    presignedUrl: value['presignedUrl'],
    publicUrl: value['publicUrl'],
  };
}
