/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PublicUser
 */
export interface PublicUser {
  /**
   *
   * @type {number}
   * @memberof PublicUser
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PublicUser
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof PublicUser
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof PublicUser
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof PublicUser
   */
  companyName: string;
  /**
   *
   * @type {string}
   * @memberof PublicUser
   */
  image: string;
}

/**
 * Check if a given object implements the PublicUser interface.
 */
export function instanceOfPublicUser(value: object): value is PublicUser {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('companyName' in value) || value['companyName'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  return true;
}

export function PublicUserFromJSON(json: any): PublicUser {
  return PublicUserFromJSONTyped(json, false);
}

export function PublicUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicUser {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    email: json['email'],
    name: json['name'],
    companyName: json['companyName'],
    image: json['image'],
  };
}

export function PublicUserToJSON(json: any): PublicUser {
  return PublicUserToJSONTyped(json, false);
}

export function PublicUserToJSONTyped(
  value?: PublicUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    email: value['email'],
    name: value['name'],
    companyName: value['companyName'],
    image: value['image'],
  };
}
