/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReviewWithDetailsAllOfMeeting
 */
export interface ReviewWithDetailsAllOfMeeting {
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  region: string;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  image: string;
  /**
   *
   * @type {Date}
   * @memberof ReviewWithDetailsAllOfMeeting
   */
  dateTime: Date;
}

/**
 * Check if a given object implements the ReviewWithDetailsAllOfMeeting interface.
 */
export function instanceOfReviewWithDetailsAllOfMeeting(
  value: object
): value is ReviewWithDetailsAllOfMeeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('region' in value) || value['region'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  return true;
}

export function ReviewWithDetailsAllOfMeetingFromJSON(json: any): ReviewWithDetailsAllOfMeeting {
  return ReviewWithDetailsAllOfMeetingFromJSONTyped(json, false);
}

export function ReviewWithDetailsAllOfMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReviewWithDetailsAllOfMeeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    type: json['type'],
    region: json['region'],
    image: json['image'],
    dateTime: new Date(json['dateTime']),
  };
}

export function ReviewWithDetailsAllOfMeetingToJSON(json: any): ReviewWithDetailsAllOfMeeting {
  return ReviewWithDetailsAllOfMeetingToJSONTyped(json, false);
}

export function ReviewWithDetailsAllOfMeetingToJSONTyped(
  value?: ReviewWithDetailsAllOfMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    type: value['type'],
    region: value['region'],
    image: value['image'],
    dateTime: value['dateTime'].toISOString(),
  };
}
