/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReviewStatistics
 */
export interface ReviewStatistics {
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  averageScore: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  totalReviews: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  oneStar: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  twoStars: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  threeStars: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  fourStars: number;
  /**
   *
   * @type {number}
   * @memberof ReviewStatistics
   */
  fiveStars: number;
}

/**
 * Check if a given object implements the ReviewStatistics interface.
 */
export function instanceOfReviewStatistics(value: object): value is ReviewStatistics {
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false;
  if (!('totalReviews' in value) || value['totalReviews'] === undefined) return false;
  if (!('oneStar' in value) || value['oneStar'] === undefined) return false;
  if (!('twoStars' in value) || value['twoStars'] === undefined) return false;
  if (!('threeStars' in value) || value['threeStars'] === undefined) return false;
  if (!('fourStars' in value) || value['fourStars'] === undefined) return false;
  if (!('fiveStars' in value) || value['fiveStars'] === undefined) return false;
  return true;
}

export function ReviewStatisticsFromJSON(json: any): ReviewStatistics {
  return ReviewStatisticsFromJSONTyped(json, false);
}

export function ReviewStatisticsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReviewStatistics {
  if (json == null) {
    return json;
  }
  return {
    averageScore: json['averageScore'],
    totalReviews: json['totalReviews'],
    oneStar: json['oneStar'],
    twoStars: json['twoStars'],
    threeStars: json['threeStars'],
    fourStars: json['fourStars'],
    fiveStars: json['fiveStars'],
  };
}

export function ReviewStatisticsToJSON(json: any): ReviewStatistics {
  return ReviewStatisticsToJSONTyped(json, false);
}

export function ReviewStatisticsToJSONTyped(
  value?: ReviewStatistics | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    averageScore: value['averageScore'],
    totalReviews: value['totalReviews'],
    oneStar: value['oneStar'],
    twoStars: value['twoStars'],
    threeStars: value['threeStars'],
    fourStars: value['fourStars'],
    fiveStars: value['fiveStars'],
  };
}
