/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  email: string;
  /**
   * 최소 8자
   * @type {string}
   * @memberof SignupRequest
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SignupRequest
   */
  companyName?: string;
}

/**
 * Check if a given object implements the SignupRequest interface.
 */
export function instanceOfSignupRequest(value: object): value is SignupRequest {
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('password' in value) || value['password'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
  return SignupRequestFromJSONTyped(json, false);
}

export function SignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
    name: json['name'],
    companyName: json['companyName'] == null ? undefined : json['companyName'],
  };
}

export function SignupRequestToJSON(json: any): SignupRequest {
  return SignupRequestToJSONTyped(json, false);
}

export function SignupRequestToJSONTyped(
  value?: SignupRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
    password: value['password'],
    name: value['name'],
    companyName: value['companyName'],
  };
}
