/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TeamIdMeetingsMeetingIdDelete200Response
 */
export interface TeamIdMeetingsMeetingIdDelete200Response {
  /**
   *
   * @type {string}
   * @memberof TeamIdMeetingsMeetingIdDelete200Response
   */
  message: string;
}

/**
 * Check if a given object implements the TeamIdMeetingsMeetingIdDelete200Response interface.
 */
export function instanceOfTeamIdMeetingsMeetingIdDelete200Response(
  value: object
): value is TeamIdMeetingsMeetingIdDelete200Response {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(
  json: any
): TeamIdMeetingsMeetingIdDelete200Response {
  return TeamIdMeetingsMeetingIdDelete200ResponseFromJSONTyped(json, false);
}

export function TeamIdMeetingsMeetingIdDelete200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TeamIdMeetingsMeetingIdDelete200Response {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function TeamIdMeetingsMeetingIdDelete200ResponseToJSON(
  json: any
): TeamIdMeetingsMeetingIdDelete200Response {
  return TeamIdMeetingsMeetingIdDelete200ResponseToJSONTyped(json, false);
}

export function TeamIdMeetingsMeetingIdDelete200ResponseToJSONTyped(
  value?: TeamIdMeetingsMeetingIdDelete200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
  };
}
