/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMeeting
 */
export interface UpdateMeeting {
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  region?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  address?: string;
  /**
   *
   * @type {number}
   * @memberof UpdateMeeting
   */
  latitude?: number;
  /**
   *
   * @type {number}
   * @memberof UpdateMeeting
   */
  longitude?: number;
  /**
   *
   * @type {Date}
   * @memberof UpdateMeeting
   */
  dateTime?: Date;
  /**
   *
   * @type {Date}
   * @memberof UpdateMeeting
   */
  registrationEnd?: Date;
  /**
   *
   * @type {number}
   * @memberof UpdateMeeting
   */
  capacity?: number;
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  image?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMeeting
   */
  description?: string;
}

/**
 * Check if a given object implements the UpdateMeeting interface.
 */
export function instanceOfUpdateMeeting(value: object): value is UpdateMeeting {
  return true;
}

export function UpdateMeetingFromJSON(json: any): UpdateMeeting {
  return UpdateMeetingFromJSONTyped(json, false);
}

export function UpdateMeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMeeting {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    type: json['type'] == null ? undefined : json['type'],
    region: json['region'] == null ? undefined : json['region'],
    address: json['address'] == null ? undefined : json['address'],
    latitude: json['latitude'] == null ? undefined : json['latitude'],
    longitude: json['longitude'] == null ? undefined : json['longitude'],
    dateTime: json['dateTime'] == null ? undefined : new Date(json['dateTime']),
    registrationEnd:
      json['registrationEnd'] == null ? undefined : new Date(json['registrationEnd']),
    capacity: json['capacity'] == null ? undefined : json['capacity'],
    image: json['image'] == null ? undefined : json['image'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function UpdateMeetingToJSON(json: any): UpdateMeeting {
  return UpdateMeetingToJSONTyped(json, false);
}

export function UpdateMeetingToJSONTyped(
  value?: UpdateMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    type: value['type'],
    region: value['region'],
    address: value['address'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    dateTime: value['dateTime'] == null ? value['dateTime'] : value['dateTime'].toISOString(),
    registrationEnd:
      value['registrationEnd'] == null
        ? value['registrationEnd']
        : value['registrationEnd'].toISOString(),
    capacity: value['capacity'],
    image: value['image'],
    description: value['description'],
  };
}
