/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMeeting } from './UserMeeting';
import {
  UserMeetingFromJSON,
  UserMeetingFromJSONTyped,
  UserMeetingToJSON,
  UserMeetingToJSONTyped,
} from './UserMeeting';

/**
 *
 * @export
 * @interface UserMeetingsResponse
 */
export interface UserMeetingsResponse {
  /**
   *
   * @type {Array<UserMeeting>}
   * @memberof UserMeetingsResponse
   */
  data: Array<UserMeeting>;
  /**
   *
   * @type {string}
   * @memberof UserMeetingsResponse
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof UserMeetingsResponse
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the UserMeetingsResponse interface.
 */
export function instanceOfUserMeetingsResponse(value: object): value is UserMeetingsResponse {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function UserMeetingsResponseFromJSON(json: any): UserMeetingsResponse {
  return UserMeetingsResponseFromJSONTyped(json, false);
}

export function UserMeetingsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserMeetingsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(UserMeetingFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function UserMeetingsResponseToJSON(json: any): UserMeetingsResponse {
  return UserMeetingsResponseToJSONTyped(json, false);
}

export function UserMeetingsResponseToJSONTyped(
  value?: UserMeetingsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(UserMeetingToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
