/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPostsResponseDataInner } from './UserPostsResponseDataInner';
import {
  UserPostsResponseDataInnerFromJSON,
  UserPostsResponseDataInnerFromJSONTyped,
  UserPostsResponseDataInnerToJSON,
  UserPostsResponseDataInnerToJSONTyped,
} from './UserPostsResponseDataInner';

/**
 *
 * @export
 * @interface UserPostsResponse
 */
export interface UserPostsResponse {
  /**
   *
   * @type {Array<UserPostsResponseDataInner>}
   * @memberof UserPostsResponse
   */
  data: Array<UserPostsResponseDataInner>;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponse
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof UserPostsResponse
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the UserPostsResponse interface.
 */
export function instanceOfUserPostsResponse(value: object): value is UserPostsResponse {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function UserPostsResponseFromJSON(json: any): UserPostsResponse {
  return UserPostsResponseFromJSONTyped(json, false);
}

export function UserPostsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPostsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(UserPostsResponseDataInnerFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function UserPostsResponseToJSON(json: any): UserPostsResponse {
  return UserPostsResponseToJSONTyped(json, false);
}

export function UserPostsResponseToJSONTyped(
  value?: UserPostsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(UserPostsResponseDataInnerToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
