/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPostsResponseDataInnerAuthor } from './UserPostsResponseDataInnerAuthor';
import {
  UserPostsResponseDataInnerAuthorFromJSON,
  UserPostsResponseDataInnerAuthorFromJSONTyped,
  UserPostsResponseDataInnerAuthorToJSON,
  UserPostsResponseDataInnerAuthorToJSONTyped,
} from './UserPostsResponseDataInnerAuthor';
import type { UserPostsResponseDataInnerCount } from './UserPostsResponseDataInnerCount';
import {
  UserPostsResponseDataInnerCountFromJSON,
  UserPostsResponseDataInnerCountFromJSONTyped,
  UserPostsResponseDataInnerCountToJSON,
  UserPostsResponseDataInnerCountToJSONTyped,
} from './UserPostsResponseDataInnerCount';

/**
 *
 * @export
 * @interface UserPostsResponseDataInner
 */
export interface UserPostsResponseDataInner {
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInner
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInner
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInner
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInner
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInner
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInner
   */
  authorId: number;
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInner
   */
  viewCount: number;
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInner
   */
  likeCount: number;
  /**
   *
   * @type {Date}
   * @memberof UserPostsResponseDataInner
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserPostsResponseDataInner
   */
  updatedAt: Date;
  /**
   *
   * @type {UserPostsResponseDataInnerAuthor}
   * @memberof UserPostsResponseDataInner
   */
  author: UserPostsResponseDataInnerAuthor;
  /**
   *
   * @type {UserPostsResponseDataInnerCount}
   * @memberof UserPostsResponseDataInner
   */
  count: UserPostsResponseDataInnerCount;
}

/**
 * Check if a given object implements the UserPostsResponseDataInner interface.
 */
export function instanceOfUserPostsResponseDataInner(
  value: object
): value is UserPostsResponseDataInner {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
  if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('author' in value) || value['author'] === undefined) return false;
  if (!('count' in value) || value['count'] === undefined) return false;
  return true;
}

export function UserPostsResponseDataInnerFromJSON(json: any): UserPostsResponseDataInner {
  return UserPostsResponseDataInnerFromJSONTyped(json, false);
}

export function UserPostsResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPostsResponseDataInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    title: json['title'],
    content: json['content'],
    image: json['image'],
    authorId: json['authorId'],
    viewCount: json['viewCount'],
    likeCount: json['likeCount'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    author: UserPostsResponseDataInnerAuthorFromJSON(json['author']),
    count: UserPostsResponseDataInnerCountFromJSON(json['_count']),
  };
}

export function UserPostsResponseDataInnerToJSON(json: any): UserPostsResponseDataInner {
  return UserPostsResponseDataInnerToJSONTyped(json, false);
}

export function UserPostsResponseDataInnerToJSONTyped(
  value?: UserPostsResponseDataInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    title: value['title'],
    content: value['content'],
    image: value['image'],
    authorId: value['authorId'],
    viewCount: value['viewCount'],
    likeCount: value['likeCount'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    author: UserPostsResponseDataInnerAuthorToJSON(value['author']),
    _count: UserPostsResponseDataInnerCountToJSON(value['count']),
  };
}
