/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserMeeting
 */
export interface UserMeeting {
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  name: string;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  dateTime: Date;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  region: string;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  participantCount: number;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  capacity: number;
  /**
   *
   * @type {boolean}
   * @memberof UserMeeting
   */
  isReviewed?: boolean;
  /**
   *
   * @type {UserMeetingRoleEnum}
   * @memberof UserMeeting
   */
  role: UserMeetingRoleEnum;
}

/**
 * @export
 */
export const UserMeetingRoleEnum = {
  Participant: 'participant',
  Host: 'host',
} as const;
export type UserMeetingRoleEnum = (typeof UserMeetingRoleEnum)[keyof typeof UserMeetingRoleEnum];

/**
 * Check if a given object implements the UserMeeting interface.
 */
export function instanceOfUserMeeting(value: object): value is UserMeeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  if (!('region' in value) || value['region'] === undefined) return false;
  if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
  if (!('capacity' in value) || value['capacity'] === undefined) return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  return true;
}

export function UserMeetingFromJSON(json: any): UserMeeting {
  return UserMeetingFromJSONTyped(json, false);
}

export function UserMeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMeeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    dateTime: new Date(json['dateTime']),
    region: json['region'],
    participantCount: json['participantCount'],
    capacity: json['capacity'],
    isReviewed: json['isReviewed'] == null ? undefined : json['isReviewed'],
    role: json['role'],
  };
}

export function UserMeetingToJSON(json: any): UserMeeting {
  return UserMeetingToJSONTyped(json, false);
}

export function UserMeetingToJSONTyped(
  value?: UserMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    dateTime: value['dateTime'].toISOString(),
    region: value['region'],
    participantCount: value['participantCount'],
    capacity: value['capacity'],
    isReviewed: value['isReviewed'],
    role: value['role'],
  };
}
