/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserPostsResponseDataInnerCount
 */
export interface UserPostsResponseDataInnerCount {
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInnerCount
   */
  comments: number;
}

/**
 * Check if a given object implements the UserPostsResponseDataInnerCount interface.
 */
export function instanceOfUserPostsResponseDataInnerCount(
  value: object
): value is UserPostsResponseDataInnerCount {
  if (!('comments' in value) || value['comments'] === undefined) return false;
  return true;
}

export function UserPostsResponseDataInnerCountFromJSON(
  json: any
): UserPostsResponseDataInnerCount {
  return UserPostsResponseDataInnerCountFromJSONTyped(json, false);
}

export function UserPostsResponseDataInnerCountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPostsResponseDataInnerCount {
  if (json == null) {
    return json;
  }
  return {
    comments: json['comments'],
  };
}

export function UserPostsResponseDataInnerCountToJSON(json: any): UserPostsResponseDataInnerCount {
  return UserPostsResponseDataInnerCountToJSONTyped(json, false);
}

export function UserPostsResponseDataInnerCountToJSONTyped(
  value?: UserPostsResponseDataInnerCount | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    comments: value['comments'],
  };
}
