/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AuthTokens,
  ErrorResponse,
  LoginRequest,
  LoginResponse,
  RefreshRequest,
  SignupRequest,
  User,
} from '../models/index';
import {
  AuthTokensFromJSON,
  AuthTokensToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
  RefreshRequestFromJSON,
  RefreshRequestToJSON,
  SignupRequestFromJSON,
  SignupRequestToJSON,
  UserFromJSON,
  UserToJSON,
} from '../models/index';

export interface AuthGoogleCallbackGetRequest {
  code: string;
  state: string;
}

export interface AuthKakaoCallbackGetRequest {
  code: string;
  state: string;
}

export interface TeamIdAuthGoogleGetRequest {
  teamId: string;
}

export interface TeamIdAuthKakaoGetRequest {
  teamId: string;
}

export interface TeamIdAuthLoginPostRequest {
  teamId: string;
  loginRequest?: LoginRequest;
}

export interface TeamIdAuthLogoutPostRequest {
  teamId: string;
  refreshRequest?: RefreshRequest;
}

export interface TeamIdAuthRefreshPostRequest {
  teamId: string;
  refreshRequest?: RefreshRequest;
}

export interface TeamIdAuthSignupPostRequest {
  teamId: string;
  signupRequest?: SignupRequest;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for authGoogleCallbackGet without sending the request
   */
  async authGoogleCallbackGetRequestOpts(
    requestParameters: AuthGoogleCallbackGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['code'] == null) {
      throw new runtime.RequiredError(
        'code',
        'Required parameter "code" was null or undefined when calling authGoogleCallbackGet().'
      );
    }

    if (requestParameters['state'] == null) {
      throw new runtime.RequiredError(
        'state',
        'Required parameter "state" was null or undefined when calling authGoogleCallbackGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['code'] != null) {
      queryParameters['code'] = requestParameters['code'];
    }

    if (requestParameters['state'] != null) {
      queryParameters['state'] = requestParameters['state'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/auth/google/callback`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 구글 로그인 완료 후 호출되는 콜백 URL입니다. 프론트엔드로 토큰과 함께 리다이렉트됩니다.
   * 구글 OAuth 콜백
   */
  async authGoogleCallbackGetRaw(
    requestParameters: AuthGoogleCallbackGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.authGoogleCallbackGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 구글 로그인 완료 후 호출되는 콜백 URL입니다. 프론트엔드로 토큰과 함께 리다이렉트됩니다.
   * 구글 OAuth 콜백
   */
  async authGoogleCallbackGet(
    requestParameters: AuthGoogleCallbackGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.authGoogleCallbackGetRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for authKakaoCallbackGet without sending the request
   */
  async authKakaoCallbackGetRequestOpts(
    requestParameters: AuthKakaoCallbackGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['code'] == null) {
      throw new runtime.RequiredError(
        'code',
        'Required parameter "code" was null or undefined when calling authKakaoCallbackGet().'
      );
    }

    if (requestParameters['state'] == null) {
      throw new runtime.RequiredError(
        'state',
        'Required parameter "state" was null or undefined when calling authKakaoCallbackGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['code'] != null) {
      queryParameters['code'] = requestParameters['code'];
    }

    if (requestParameters['state'] != null) {
      queryParameters['state'] = requestParameters['state'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/auth/kakao/callback`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 카카오 로그인 완료 후 호출되는 콜백 URL입니다. 프론트엔드로 토큰과 함께 리다이렉트됩니다.
   * 카카오 OAuth 콜백
   */
  async authKakaoCallbackGetRaw(
    requestParameters: AuthKakaoCallbackGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.authKakaoCallbackGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 카카오 로그인 완료 후 호출되는 콜백 URL입니다. 프론트엔드로 토큰과 함께 리다이렉트됩니다.
   * 카카오 OAuth 콜백
   */
  async authKakaoCallbackGet(
    requestParameters: AuthKakaoCallbackGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.authKakaoCallbackGetRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for teamIdAuthGoogleGet without sending the request
   */
  async teamIdAuthGoogleGetRequestOpts(
    requestParameters: TeamIdAuthGoogleGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthGoogleGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/google`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 구글 소셜 로그인을 시작합니다. 구글 로그인 페이지로 리다이렉트됩니다.
   * 구글 OAuth 시작
   */
  async teamIdAuthGoogleGetRaw(
    requestParameters: TeamIdAuthGoogleGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.teamIdAuthGoogleGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 구글 소셜 로그인을 시작합니다. 구글 로그인 페이지로 리다이렉트됩니다.
   * 구글 OAuth 시작
   */
  async teamIdAuthGoogleGet(
    requestParameters: TeamIdAuthGoogleGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.teamIdAuthGoogleGetRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for teamIdAuthKakaoGet without sending the request
   */
  async teamIdAuthKakaoGetRequestOpts(
    requestParameters: TeamIdAuthKakaoGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthKakaoGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/kakao`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 카카오 소셜 로그인을 시작합니다. 카카오 로그인 페이지로 리다이렉트됩니다.
   * 카카오 OAuth 시작
   */
  async teamIdAuthKakaoGetRaw(
    requestParameters: TeamIdAuthKakaoGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.teamIdAuthKakaoGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 카카오 소셜 로그인을 시작합니다. 카카오 로그인 페이지로 리다이렉트됩니다.
   * 카카오 OAuth 시작
   */
  async teamIdAuthKakaoGet(
    requestParameters: TeamIdAuthKakaoGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.teamIdAuthKakaoGetRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for teamIdAuthLoginPost without sending the request
   */
  async teamIdAuthLoginPostRequestOpts(
    requestParameters: TeamIdAuthLoginPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthLoginPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/login`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters['loginRequest']),
    };
  }

  /**
   * 이메일과 비밀번호로 로그인합니다. 성공 시 accessToken(15분)과 refreshToken(7일)을 발급합니다.
   * 로그인
   */
  async teamIdAuthLoginPostRaw(
    requestParameters: TeamIdAuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions = await this.teamIdAuthLoginPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
  }

  /**
   * 이메일과 비밀번호로 로그인합니다. 성공 시 accessToken(15분)과 refreshToken(7일)을 발급합니다.
   * 로그인
   */
  async teamIdAuthLoginPost(
    requestParameters: TeamIdAuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.teamIdAuthLoginPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdAuthLogoutPost without sending the request
   */
  async teamIdAuthLogoutPostRequestOpts(
    requestParameters: TeamIdAuthLogoutPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthLogoutPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/logout`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RefreshRequestToJSON(requestParameters['refreshRequest']),
    };
  }

  /**
   * 현재 로그인된 세션을 종료합니다. 특정 리프레시 토큰만 무효화됩니다.
   * 로그아웃
   */
  async teamIdAuthLogoutPostRaw(
    requestParameters: TeamIdAuthLogoutPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.teamIdAuthLogoutPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 현재 로그인된 세션을 종료합니다. 특정 리프레시 토큰만 무효화됩니다.
   * 로그아웃
   */
  async teamIdAuthLogoutPost(
    requestParameters: TeamIdAuthLogoutPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.teamIdAuthLogoutPostRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for teamIdAuthRefreshPost without sending the request
   */
  async teamIdAuthRefreshPostRequestOpts(
    requestParameters: TeamIdAuthRefreshPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthRefreshPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/refresh`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RefreshRequestToJSON(requestParameters['refreshRequest']),
    };
  }

  /**
   * 리프레시 토큰으로 새로운 accessToken과 refreshToken을 발급받습니다. 기존 리프레시 토큰은 무효화됩니다 (토큰 로테이션).
   * 토큰 갱신
   */
  async teamIdAuthRefreshPostRaw(
    requestParameters: TeamIdAuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthTokens>> {
    const requestOptions = await this.teamIdAuthRefreshPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokensFromJSON(jsonValue));
  }

  /**
   * 리프레시 토큰으로 새로운 accessToken과 refreshToken을 발급받습니다. 기존 리프레시 토큰은 무효화됩니다 (토큰 로테이션).
   * 토큰 갱신
   */
  async teamIdAuthRefreshPost(
    requestParameters: TeamIdAuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthTokens> {
    const response = await this.teamIdAuthRefreshPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdAuthSignupPost without sending the request
   */
  async teamIdAuthSignupPostRequestOpts(
    requestParameters: TeamIdAuthSignupPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthSignupPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/signup`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: SignupRequestToJSON(requestParameters['signupRequest']),
    };
  }

  /**
   * 새로운 사용자를 등록합니다. 이메일은 팀 내에서 고유해야 합니다.
   * 회원가입
   */
  async teamIdAuthSignupPostRaw(
    requestParameters: TeamIdAuthSignupPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const requestOptions = await this.teamIdAuthSignupPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * 새로운 사용자를 등록합니다. 이메일은 팀 내에서 고유해야 합니다.
   * 회원가입
   */
  async teamIdAuthSignupPost(
    requestParameters: TeamIdAuthSignupPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.teamIdAuthSignupPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
