/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CreateMeetingType,
  ErrorResponse,
  MeetingType,
  TeamIdMeetingsMeetingIdDelete200Response,
  UpdateMeetingType,
} from '../models/index';
import {
  CreateMeetingTypeFromJSON,
  CreateMeetingTypeToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  MeetingTypeFromJSON,
  MeetingTypeToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
  UpdateMeetingTypeFromJSON,
  UpdateMeetingTypeToJSON,
} from '../models/index';

export interface TeamIdMeetingTypesGetRequest {
  teamId: string;
}

export interface TeamIdMeetingTypesPostRequest {
  teamId: string;
  createMeetingType?: CreateMeetingType;
}

export interface TeamIdMeetingTypesTypeIdDeleteRequest {
  teamId: string;
  typeId: number;
}

export interface TeamIdMeetingTypesTypeIdPatchRequest {
  teamId: string;
  typeId: number;
  updateMeetingType?: UpdateMeetingType;
}

/**
 *
 */
export class MeetingTypesApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdMeetingTypesGet without sending the request
   */
  async teamIdMeetingTypesGetRequestOpts(
    requestParameters: TeamIdMeetingTypesGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingTypesGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meeting-types`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 팀의 모임 종류 목록을 조회합니다.
   * 모임 종류 목록
   */
  async teamIdMeetingTypesGetRaw(
    requestParameters: TeamIdMeetingTypesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<MeetingType>>> {
    const requestOptions = await this.teamIdMeetingTypesGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MeetingTypeFromJSON));
  }

  /**
   * 팀의 모임 종류 목록을 조회합니다.
   * 모임 종류 목록
   */
  async teamIdMeetingTypesGet(
    requestParameters: TeamIdMeetingTypesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<MeetingType>> {
    const response = await this.teamIdMeetingTypesGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingTypesPost without sending the request
   */
  async teamIdMeetingTypesPostRequestOpts(
    requestParameters: TeamIdMeetingTypesPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingTypesPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meeting-types`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateMeetingTypeToJSON(requestParameters['createMeetingType']),
    };
  }

  /**
   * 새로운 모임 종류를 생성합니다. 팀 내에서 이름은 고유해야 합니다.
   * 모임 종류 생성
   */
  async teamIdMeetingTypesPostRaw(
    requestParameters: TeamIdMeetingTypesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingType>> {
    const requestOptions = await this.teamIdMeetingTypesPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingTypeFromJSON(jsonValue));
  }

  /**
   * 새로운 모임 종류를 생성합니다. 팀 내에서 이름은 고유해야 합니다.
   * 모임 종류 생성
   */
  async teamIdMeetingTypesPost(
    requestParameters: TeamIdMeetingTypesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingType> {
    const response = await this.teamIdMeetingTypesPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingTypesTypeIdDelete without sending the request
   */
  async teamIdMeetingTypesTypeIdDeleteRequestOpts(
    requestParameters: TeamIdMeetingTypesTypeIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingTypesTypeIdDelete().'
      );
    }

    if (requestParameters['typeId'] == null) {
      throw new runtime.RequiredError(
        'typeId',
        'Required parameter "typeId" was null or undefined when calling teamIdMeetingTypesTypeIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meeting-types/{typeId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'typeId'}}`,
      encodeURIComponent(String(requestParameters['typeId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임 종류를 삭제합니다.
   * 모임 종류 삭제
   */
  async teamIdMeetingTypesTypeIdDeleteRaw(
    requestParameters: TeamIdMeetingTypesTypeIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdMeetingTypesTypeIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 모임 종류를 삭제합니다.
   * 모임 종류 삭제
   */
  async teamIdMeetingTypesTypeIdDelete(
    requestParameters: TeamIdMeetingTypesTypeIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdMeetingTypesTypeIdDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingTypesTypeIdPatch without sending the request
   */
  async teamIdMeetingTypesTypeIdPatchRequestOpts(
    requestParameters: TeamIdMeetingTypesTypeIdPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingTypesTypeIdPatch().'
      );
    }

    if (requestParameters['typeId'] == null) {
      throw new runtime.RequiredError(
        'typeId',
        'Required parameter "typeId" was null or undefined when calling teamIdMeetingTypesTypeIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meeting-types/{typeId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'typeId'}}`,
      encodeURIComponent(String(requestParameters['typeId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateMeetingTypeToJSON(requestParameters['updateMeetingType']),
    };
  }

  /**
   * 모임 종류 정보를 수정합니다.
   * 모임 종류 수정
   */
  async teamIdMeetingTypesTypeIdPatchRaw(
    requestParameters: TeamIdMeetingTypesTypeIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingType>> {
    const requestOptions = await this.teamIdMeetingTypesTypeIdPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingTypeFromJSON(jsonValue));
  }

  /**
   * 모임 종류 정보를 수정합니다.
   * 모임 종류 수정
   */
  async teamIdMeetingTypesTypeIdPatch(
    requestParameters: TeamIdMeetingTypesTypeIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingType> {
    const response = await this.teamIdMeetingTypesTypeIdPatchRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
