/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Notification,
  NotificationList,
  TeamIdMeetingsMeetingIdDelete200Response,
  TeamIdNotificationsDelete200Response,
} from '../models/index';
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  NotificationFromJSON,
  NotificationToJSON,
  NotificationListFromJSON,
  NotificationListToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
  TeamIdNotificationsDelete200ResponseFromJSON,
  TeamIdNotificationsDelete200ResponseToJSON,
} from '../models/index';

export interface TeamIdNotificationsDeleteRequest {
  teamId: string;
}

export interface TeamIdNotificationsGetRequest {
  teamId: string;
  isRead?: TeamIdNotificationsGetIsReadEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdNotificationsNotificationIdDeleteRequest {
  teamId: string;
  notificationId: number;
}

export interface TeamIdNotificationsNotificationIdReadPutRequest {
  teamId: string;
  notificationId: number;
}

export interface TeamIdNotificationsReadAllPutRequest {
  teamId: string;
}

/**
 *
 */
export class NotificationsApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdNotificationsDelete without sending the request
   */
  async teamIdNotificationsDeleteRequestOpts(
    requestParameters: TeamIdNotificationsDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdNotificationsDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/notifications`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 사용자의 모든 알림을 삭제합니다.
   * 전체 알림 삭제
   */
  async teamIdNotificationsDeleteRaw(
    requestParameters: TeamIdNotificationsDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdNotificationsDelete200Response>> {
    const requestOptions = await this.teamIdNotificationsDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdNotificationsDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 현재 사용자의 모든 알림을 삭제합니다.
   * 전체 알림 삭제
   */
  async teamIdNotificationsDelete(
    requestParameters: TeamIdNotificationsDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdNotificationsDelete200Response> {
    const response = await this.teamIdNotificationsDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdNotificationsGet without sending the request
   */
  async teamIdNotificationsGetRequestOpts(
    requestParameters: TeamIdNotificationsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdNotificationsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['isRead'] != null) {
      queryParameters['isRead'] = requestParameters['isRead'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/notifications`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 사용자의 알림 목록을 조회합니다.  - 알림 종류: 개설 확정(MEETING_CONFIRMED), 모임 취소(MEETING_CANCELED), 댓글(COMMENT) - isRead 파라미터로 읽음/미읽음 필터링 가능
   * 알림 목록
   */
  async teamIdNotificationsGetRaw(
    requestParameters: TeamIdNotificationsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<NotificationList>> {
    const requestOptions = await this.teamIdNotificationsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      NotificationListFromJSON(jsonValue)
    );
  }

  /**
   * 현재 사용자의 알림 목록을 조회합니다.  - 알림 종류: 개설 확정(MEETING_CONFIRMED), 모임 취소(MEETING_CANCELED), 댓글(COMMENT) - isRead 파라미터로 읽음/미읽음 필터링 가능
   * 알림 목록
   */
  async teamIdNotificationsGet(
    requestParameters: TeamIdNotificationsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<NotificationList> {
    const response = await this.teamIdNotificationsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdNotificationsNotificationIdDelete without sending the request
   */
  async teamIdNotificationsNotificationIdDeleteRequestOpts(
    requestParameters: TeamIdNotificationsNotificationIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdNotificationsNotificationIdDelete().'
      );
    }

    if (requestParameters['notificationId'] == null) {
      throw new runtime.RequiredError(
        'notificationId',
        'Required parameter "notificationId" was null or undefined when calling teamIdNotificationsNotificationIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/notifications/{notificationId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'notificationId'}}`,
      encodeURIComponent(String(requestParameters['notificationId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 알림을 삭제합니다.
   * 알림 삭제
   */
  async teamIdNotificationsNotificationIdDeleteRaw(
    requestParameters: TeamIdNotificationsNotificationIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions =
      await this.teamIdNotificationsNotificationIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 특정 알림을 삭제합니다.
   * 알림 삭제
   */
  async teamIdNotificationsNotificationIdDelete(
    requestParameters: TeamIdNotificationsNotificationIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdNotificationsNotificationIdDeleteRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdNotificationsNotificationIdReadPut without sending the request
   */
  async teamIdNotificationsNotificationIdReadPutRequestOpts(
    requestParameters: TeamIdNotificationsNotificationIdReadPutRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdNotificationsNotificationIdReadPut().'
      );
    }

    if (requestParameters['notificationId'] == null) {
      throw new runtime.RequiredError(
        'notificationId',
        'Required parameter "notificationId" was null or undefined when calling teamIdNotificationsNotificationIdReadPut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/notifications/{notificationId}/read`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'notificationId'}}`,
      encodeURIComponent(String(requestParameters['notificationId']))
    );

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 알림을 읽음으로 표시합니다.
   * 알림 읽음 처리
   */
  async teamIdNotificationsNotificationIdReadPutRaw(
    requestParameters: TeamIdNotificationsNotificationIdReadPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Notification>> {
    const requestOptions =
      await this.teamIdNotificationsNotificationIdReadPutRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => NotificationFromJSON(jsonValue));
  }

  /**
   * 특정 알림을 읽음으로 표시합니다.
   * 알림 읽음 처리
   */
  async teamIdNotificationsNotificationIdReadPut(
    requestParameters: TeamIdNotificationsNotificationIdReadPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Notification> {
    const response = await this.teamIdNotificationsNotificationIdReadPutRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdNotificationsReadAllPut without sending the request
   */
  async teamIdNotificationsReadAllPutRequestOpts(
    requestParameters: TeamIdNotificationsReadAllPutRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdNotificationsReadAllPut().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/notifications/read-all`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'PUT',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모든 읽지 않은 알림을 읽음으로 표시합니다.
   * 모든 알림 읽음 처리
   */
  async teamIdNotificationsReadAllPutRaw(
    requestParameters: TeamIdNotificationsReadAllPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdNotificationsDelete200Response>> {
    const requestOptions = await this.teamIdNotificationsReadAllPutRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdNotificationsDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 모든 읽지 않은 알림을 읽음으로 표시합니다.
   * 모든 알림 읽음 처리
   */
  async teamIdNotificationsReadAllPut(
    requestParameters: TeamIdNotificationsReadAllPutRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdNotificationsDelete200Response> {
    const response = await this.teamIdNotificationsReadAllPutRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdNotificationsGetIsReadEnum = {
  True: 'true',
  False: 'false',
} as const;
export type TeamIdNotificationsGetIsReadEnum =
  (typeof TeamIdNotificationsGetIsReadEnum)[keyof typeof TeamIdNotificationsGetIsReadEnum];
