/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { OgMetadata } from '../models/index';
import { OgMetadataFromJSON, OgMetadataToJSON } from '../models/index';

export interface OgGetRequest {
  url: string;
}

/**
 *
 */
export class OGApi extends runtime.BaseAPI {
  /**
   * Creates request options for ogGet without sending the request
   */
  async ogGetRequestOpts(requestParameters: OgGetRequest): Promise<runtime.RequestOpts> {
    if (requestParameters['url'] == null) {
      throw new runtime.RequiredError(
        'url',
        'Required parameter "url" was null or undefined when calling ogGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['url'] != null) {
      queryParameters['url'] = requestParameters['url'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/og`;

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 주어진 URL에서 Open Graph 메타데이터(제목, 설명, 이미지 등)를 파싱하여 반환합니다.
   * URL의 Open Graph 메타데이터 조회
   */
  async ogGetRaw(
    requestParameters: OgGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<OgMetadata>> {
    const requestOptions = await this.ogGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => OgMetadataFromJSON(jsonValue));
  }

  /**
   * 주어진 URL에서 Open Graph 메타데이터(제목, 설명, 이미지 등)를 파싱하여 반환합니다.
   * URL의 Open Graph 메타데이터 조회
   */
  async ogGet(
    requestParameters: OgGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<OgMetadata> {
    const response = await this.ogGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
