/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Comment,
  CommentList,
  CreateComment,
  CreatePost,
  ErrorResponse,
  PostLike,
  PostList,
  PostWithAuthor,
  PostWithComments,
  TeamIdMeetingsMeetingIdDelete200Response,
  UpdateComment,
  UpdatePost,
} from '../models/index';
import {
  CommentFromJSON,
  CommentToJSON,
  CommentListFromJSON,
  CommentListToJSON,
  CreateCommentFromJSON,
  CreateCommentToJSON,
  CreatePostFromJSON,
  CreatePostToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  PostLikeFromJSON,
  PostLikeToJSON,
  PostListFromJSON,
  PostListToJSON,
  PostWithAuthorFromJSON,
  PostWithAuthorToJSON,
  PostWithCommentsFromJSON,
  PostWithCommentsToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
  UpdateCommentFromJSON,
  UpdateCommentToJSON,
  UpdatePostFromJSON,
  UpdatePostToJSON,
} from '../models/index';

export interface TeamIdPostsGetRequest {
  teamId: string;
  type?: TeamIdPostsGetTypeEnum;
  keyword?: string;
  sortBy?: TeamIdPostsGetSortByEnum;
  sortOrder?: TeamIdPostsGetSortOrderEnum;
  cursor?: string;
  offset?: number;
  limit?: number;
  size?: number;
}

export interface TeamIdPostsPostRequest {
  teamId: string;
  createPost?: CreatePost;
}

export interface TeamIdPostsPostIdCommentsCommentIdDeleteRequest {
  teamId: string;
  postId: number;
  commentId: number;
}

export interface TeamIdPostsPostIdCommentsCommentIdPatchRequest {
  teamId: string;
  postId: number;
  commentId: number;
  updateComment?: UpdateComment;
}

export interface TeamIdPostsPostIdCommentsGetRequest {
  teamId: string;
  postId: number;
  sortBy?: TeamIdPostsPostIdCommentsGetSortByEnum;
  sortOrder?: TeamIdPostsPostIdCommentsGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdPostsPostIdCommentsPostRequest {
  teamId: string;
  postId: number;
  createComment?: CreateComment;
}

export interface TeamIdPostsPostIdDeleteRequest {
  teamId: string;
  postId: number;
}

export interface TeamIdPostsPostIdGetRequest {
  teamId: string;
  postId: number;
}

export interface TeamIdPostsPostIdLikeDeleteRequest {
  teamId: string;
  postId: number;
}

export interface TeamIdPostsPostIdLikePostRequest {
  teamId: string;
  postId: number;
}

export interface TeamIdPostsPostIdPatchRequest {
  teamId: string;
  postId: number;
  updatePost?: UpdatePost;
}

/**
 *
 */
export class PostsApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdPostsGet without sending the request
   */
  async teamIdPostsGetRequestOpts(
    requestParameters: TeamIdPostsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['keyword'] != null) {
      queryParameters['keyword'] = requestParameters['keyword'];
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['offset'] != null) {
      queryParameters['offset'] = requestParameters['offset'];
    }

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글 목록을 조회합니다.  **조회 타입:** - type=all: 전체 게시글 (기본값, 최신순) - type=best: 베스트 게시글 (최근 30일 내 작성, likeCount 높은 순)  **정렬 기준 (sortBy):** - createdAt: 작성일순 (기본값) - viewCount: 조회수순 - likeCount: 좋아요순 - commentCount: 댓글 많은 순  **페이지네이션:** - 커서 기반: cursor (이전 응답의 nextCursor) + size (기본 10, 최대 100) - 오프셋 기반: offset (건너뛸 항목 수) + limit (기본 10, 최대 100) - offset 사용 시 응답에 totalCount 포함, cursor/nextCursor 미포함
   * 게시글 목록
   */
  async teamIdPostsGetRaw(
    requestParameters: TeamIdPostsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostList>> {
    const requestOptions = await this.teamIdPostsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PostListFromJSON(jsonValue));
  }

  /**
   * 게시글 목록을 조회합니다.  **조회 타입:** - type=all: 전체 게시글 (기본값, 최신순) - type=best: 베스트 게시글 (최근 30일 내 작성, likeCount 높은 순)  **정렬 기준 (sortBy):** - createdAt: 작성일순 (기본값) - viewCount: 조회수순 - likeCount: 좋아요순 - commentCount: 댓글 많은 순  **페이지네이션:** - 커서 기반: cursor (이전 응답의 nextCursor) + size (기본 10, 최대 100) - 오프셋 기반: offset (건너뛸 항목 수) + limit (기본 10, 최대 100) - offset 사용 시 응답에 totalCount 포함, cursor/nextCursor 미포함
   * 게시글 목록
   */
  async teamIdPostsGet(
    requestParameters: TeamIdPostsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostList> {
    const response = await this.teamIdPostsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPost without sending the request
   */
  async teamIdPostsPostRequestOpts(
    requestParameters: TeamIdPostsPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreatePostToJSON(requestParameters['createPost']),
    };
  }

  /**
   * 새로운 게시글을 작성합니다.  **비즈니스 규칙:** - 제목(title)은 필수이며 최소 1자 이상 - 내용(content)은 필수이며 최소 1자 이상 - 이미지(image)는 선택 사항 - 작성 시 likeCount와 viewCount는 0으로 초기화
   * 게시글 작성
   */
  async teamIdPostsPostRaw(
    requestParameters: TeamIdPostsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostWithAuthor>> {
    const requestOptions = await this.teamIdPostsPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PostWithAuthorFromJSON(jsonValue));
  }

  /**
   * 새로운 게시글을 작성합니다.  **비즈니스 규칙:** - 제목(title)은 필수이며 최소 1자 이상 - 내용(content)은 필수이며 최소 1자 이상 - 이미지(image)는 선택 사항 - 작성 시 likeCount와 viewCount는 0으로 초기화
   * 게시글 작성
   */
  async teamIdPostsPost(
    requestParameters: TeamIdPostsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostWithAuthor> {
    const response = await this.teamIdPostsPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdCommentsCommentIdDelete without sending the request
   */
  async teamIdPostsPostIdCommentsCommentIdDeleteRequestOpts(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdDelete().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdDelete().'
      );
    }

    if (requestParameters['commentId'] == null) {
      throw new runtime.RequiredError(
        'commentId',
        'Required parameter "commentId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/comments/{commentId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );
    urlPath = urlPath.replace(
      `{${'commentId'}}`,
      encodeURIComponent(String(requestParameters['commentId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 댓글을 삭제합니다. 작성자만 삭제할 수 있습니다.
   * 댓글 삭제
   */
  async teamIdPostsPostIdCommentsCommentIdDeleteRaw(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions =
      await this.teamIdPostsPostIdCommentsCommentIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 댓글을 삭제합니다. 작성자만 삭제할 수 있습니다.
   * 댓글 삭제
   */
  async teamIdPostsPostIdCommentsCommentIdDelete(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdPostsPostIdCommentsCommentIdDeleteRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdCommentsCommentIdPatch without sending the request
   */
  async teamIdPostsPostIdCommentsCommentIdPatchRequestOpts(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdPatch().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdPatch().'
      );
    }

    if (requestParameters['commentId'] == null) {
      throw new runtime.RequiredError(
        'commentId',
        'Required parameter "commentId" was null or undefined when calling teamIdPostsPostIdCommentsCommentIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/comments/{commentId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );
    urlPath = urlPath.replace(
      `{${'commentId'}}`,
      encodeURIComponent(String(requestParameters['commentId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateCommentToJSON(requestParameters['updateComment']),
    };
  }

  /**
   * 댓글을 수정합니다. 작성자만 수정할 수 있습니다.
   * 댓글 수정
   */
  async teamIdPostsPostIdCommentsCommentIdPatchRaw(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Comment>> {
    const requestOptions =
      await this.teamIdPostsPostIdCommentsCommentIdPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CommentFromJSON(jsonValue));
  }

  /**
   * 댓글을 수정합니다. 작성자만 수정할 수 있습니다.
   * 댓글 수정
   */
  async teamIdPostsPostIdCommentsCommentIdPatch(
    requestParameters: TeamIdPostsPostIdCommentsCommentIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Comment> {
    const response = await this.teamIdPostsPostIdCommentsCommentIdPatchRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdCommentsGet without sending the request
   */
  async teamIdPostsPostIdCommentsGetRequestOpts(
    requestParameters: TeamIdPostsPostIdCommentsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdCommentsGet().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdCommentsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/comments`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글의 댓글 목록을 조회합니다.
   * 댓글 목록
   */
  async teamIdPostsPostIdCommentsGetRaw(
    requestParameters: TeamIdPostsPostIdCommentsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<CommentList>> {
    const requestOptions = await this.teamIdPostsPostIdCommentsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CommentListFromJSON(jsonValue));
  }

  /**
   * 게시글의 댓글 목록을 조회합니다.
   * 댓글 목록
   */
  async teamIdPostsPostIdCommentsGet(
    requestParameters: TeamIdPostsPostIdCommentsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<CommentList> {
    const response = await this.teamIdPostsPostIdCommentsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdCommentsPost without sending the request
   */
  async teamIdPostsPostIdCommentsPostRequestOpts(
    requestParameters: TeamIdPostsPostIdCommentsPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdCommentsPost().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdCommentsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/comments`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateCommentToJSON(requestParameters['createComment']),
    };
  }

  /**
   * 게시글에 댓글을 작성합니다.  - 게시글 작성자에게 알림이 발생합니다 (본인 댓글 제외)
   * 댓글 작성
   */
  async teamIdPostsPostIdCommentsPostRaw(
    requestParameters: TeamIdPostsPostIdCommentsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Comment>> {
    const requestOptions = await this.teamIdPostsPostIdCommentsPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => CommentFromJSON(jsonValue));
  }

  /**
   * 게시글에 댓글을 작성합니다.  - 게시글 작성자에게 알림이 발생합니다 (본인 댓글 제외)
   * 댓글 작성
   */
  async teamIdPostsPostIdCommentsPost(
    requestParameters: TeamIdPostsPostIdCommentsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Comment> {
    const response = await this.teamIdPostsPostIdCommentsPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdDelete without sending the request
   */
  async teamIdPostsPostIdDeleteRequestOpts(
    requestParameters: TeamIdPostsPostIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdDelete().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글을 삭제합니다. 작성자만 삭제할 수 있습니다.
   * 게시글 삭제
   */
  async teamIdPostsPostIdDeleteRaw(
    requestParameters: TeamIdPostsPostIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdPostsPostIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 게시글을 삭제합니다. 작성자만 삭제할 수 있습니다.
   * 게시글 삭제
   */
  async teamIdPostsPostIdDelete(
    requestParameters: TeamIdPostsPostIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdPostsPostIdDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdGet without sending the request
   */
  async teamIdPostsPostIdGetRequestOpts(
    requestParameters: TeamIdPostsPostIdGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdGet().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글 상세 정보를 조회합니다. 조회 시 조회수가 증가합니다.
   * 게시글 상세
   */
  async teamIdPostsPostIdGetRaw(
    requestParameters: TeamIdPostsPostIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostWithComments>> {
    const requestOptions = await this.teamIdPostsPostIdGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PostWithCommentsFromJSON(jsonValue)
    );
  }

  /**
   * 게시글 상세 정보를 조회합니다. 조회 시 조회수가 증가합니다.
   * 게시글 상세
   */
  async teamIdPostsPostIdGet(
    requestParameters: TeamIdPostsPostIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostWithComments> {
    const response = await this.teamIdPostsPostIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdLikeDelete without sending the request
   */
  async teamIdPostsPostIdLikeDeleteRequestOpts(
    requestParameters: TeamIdPostsPostIdLikeDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdLikeDelete().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdLikeDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/like`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글의 좋아요를 취소합니다.
   * 좋아요 취소
   */
  async teamIdPostsPostIdLikeDeleteRaw(
    requestParameters: TeamIdPostsPostIdLikeDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdPostsPostIdLikeDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 게시글의 좋아요를 취소합니다.
   * 좋아요 취소
   */
  async teamIdPostsPostIdLikeDelete(
    requestParameters: TeamIdPostsPostIdLikeDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdPostsPostIdLikeDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdLikePost without sending the request
   */
  async teamIdPostsPostIdLikePostRequestOpts(
    requestParameters: TeamIdPostsPostIdLikePostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdLikePost().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdLikePost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}/like`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 게시글에 좋아요를 추가합니다.
   * 좋아요 추가
   */
  async teamIdPostsPostIdLikePostRaw(
    requestParameters: TeamIdPostsPostIdLikePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostLike>> {
    const requestOptions = await this.teamIdPostsPostIdLikePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PostLikeFromJSON(jsonValue));
  }

  /**
   * 게시글에 좋아요를 추가합니다.
   * 좋아요 추가
   */
  async teamIdPostsPostIdLikePost(
    requestParameters: TeamIdPostsPostIdLikePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostLike> {
    const response = await this.teamIdPostsPostIdLikePostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdPostsPostIdPatch without sending the request
   */
  async teamIdPostsPostIdPatchRequestOpts(
    requestParameters: TeamIdPostsPostIdPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdPostsPostIdPatch().'
      );
    }

    if (requestParameters['postId'] == null) {
      throw new runtime.RequiredError(
        'postId',
        'Required parameter "postId" was null or undefined when calling teamIdPostsPostIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/posts/{postId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'postId'}}`,
      encodeURIComponent(String(requestParameters['postId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdatePostToJSON(requestParameters['updatePost']),
    };
  }

  /**
   * 게시글을 수정합니다.  **비즈니스 규칙:** - 작성자만 수정할 수 있습니다 - 제목, 내용, 이미지를 개별적으로 수정 가능 - likeCount와 viewCount는 수정되지 않습니다
   * 게시글 수정
   */
  async teamIdPostsPostIdPatchRaw(
    requestParameters: TeamIdPostsPostIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PostWithAuthor>> {
    const requestOptions = await this.teamIdPostsPostIdPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PostWithAuthorFromJSON(jsonValue));
  }

  /**
   * 게시글을 수정합니다.  **비즈니스 규칙:** - 작성자만 수정할 수 있습니다 - 제목, 내용, 이미지를 개별적으로 수정 가능 - likeCount와 viewCount는 수정되지 않습니다
   * 게시글 수정
   */
  async teamIdPostsPostIdPatch(
    requestParameters: TeamIdPostsPostIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PostWithAuthor> {
    const response = await this.teamIdPostsPostIdPatchRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdPostsGetTypeEnum = {
  All: 'all',
  Best: 'best',
} as const;
export type TeamIdPostsGetTypeEnum =
  (typeof TeamIdPostsGetTypeEnum)[keyof typeof TeamIdPostsGetTypeEnum];
/**
 * @export
 */
export const TeamIdPostsGetSortByEnum = {
  CreatedAt: 'createdAt',
  ViewCount: 'viewCount',
  LikeCount: 'likeCount',
  CommentCount: 'commentCount',
} as const;
export type TeamIdPostsGetSortByEnum =
  (typeof TeamIdPostsGetSortByEnum)[keyof typeof TeamIdPostsGetSortByEnum];
/**
 * @export
 */
export const TeamIdPostsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdPostsGetSortOrderEnum =
  (typeof TeamIdPostsGetSortOrderEnum)[keyof typeof TeamIdPostsGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdPostsPostIdCommentsGetSortByEnum = {
  CreatedAt: 'createdAt',
} as const;
export type TeamIdPostsPostIdCommentsGetSortByEnum =
  (typeof TeamIdPostsPostIdCommentsGetSortByEnum)[keyof typeof TeamIdPostsPostIdCommentsGetSortByEnum];
/**
 * @export
 */
export const TeamIdPostsPostIdCommentsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdPostsPostIdCommentsGetSortOrderEnum =
  (typeof TeamIdPostsPostIdCommentsGetSortOrderEnum)[keyof typeof TeamIdPostsPostIdCommentsGetSortOrderEnum];
