/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PublicUser,
  UpdateUserRequest,
  User,
  UserMeetingsResponse,
  UserPostsResponse,
  UserReviewsResponse,
} from '../models/index';
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  PublicUserFromJSON,
  PublicUserToJSON,
  UpdateUserRequestFromJSON,
  UpdateUserRequestToJSON,
  UserFromJSON,
  UserToJSON,
  UserMeetingsResponseFromJSON,
  UserMeetingsResponseToJSON,
  UserPostsResponseFromJSON,
  UserPostsResponseToJSON,
  UserReviewsResponseFromJSON,
  UserReviewsResponseToJSON,
} from '../models/index';

export interface TeamIdUsersMeGetRequest {
  teamId: string;
}

export interface TeamIdUsersMeMeetingsGetRequest {
  teamId: string;
  type?: TeamIdUsersMeMeetingsGetTypeEnum;
  completed?: TeamIdUsersMeMeetingsGetCompletedEnum;
  reviewed?: TeamIdUsersMeMeetingsGetReviewedEnum;
  sortBy?: TeamIdUsersMeMeetingsGetSortByEnum;
  sortOrder?: TeamIdUsersMeMeetingsGetSortOrderEnum;
  size?: number;
  cursor?: string;
}

export interface TeamIdUsersMePatchRequest {
  teamId: string;
  updateUserRequest?: UpdateUserRequest;
}

export interface TeamIdUsersMePostsGetRequest {
  teamId: string;
  sortBy?: TeamIdUsersMePostsGetSortByEnum;
  sortOrder?: TeamIdUsersMePostsGetSortOrderEnum;
  size?: number;
  cursor?: string;
}

export interface TeamIdUsersMeReviewsGetRequest {
  teamId: string;
  sortBy?: TeamIdUsersMeReviewsGetSortByEnum;
  sortOrder?: TeamIdUsersMeReviewsGetSortOrderEnum;
  size?: number;
  cursor?: string;
}

export interface TeamIdUsersUserIdGetRequest {
  teamId: string;
  userId: number;
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdUsersMeGet without sending the request
   */
  async teamIdUsersMeGetRequestOpts(
    requestParameters: TeamIdUsersMeGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersMeGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/me`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 로그인된 사용자의 정보를 조회합니다. Authorization 헤더에 Bearer 토큰이 필요합니다.
   * 내 정보 조회
   */
  async teamIdUsersMeGetRaw(
    requestParameters: TeamIdUsersMeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const requestOptions = await this.teamIdUsersMeGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * 현재 로그인된 사용자의 정보를 조회합니다. Authorization 헤더에 Bearer 토큰이 필요합니다.
   * 내 정보 조회
   */
  async teamIdUsersMeGet(
    requestParameters: TeamIdUsersMeGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.teamIdUsersMeGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdUsersMeMeetingsGet without sending the request
   */
  async teamIdUsersMeMeetingsGetRequestOpts(
    requestParameters: TeamIdUsersMeMeetingsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersMeMeetingsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['completed'] != null) {
      queryParameters['completed'] = requestParameters['completed'];
    }

    if (requestParameters['reviewed'] != null) {
      queryParameters['reviewed'] = requestParameters['reviewed'];
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/me/meetings`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 로그인된 사용자의 모임 목록을 조회합니다. 필터와 정렬 옵션을 지원합니다.
   * 내가 참여한/만든 모임 목록 조회
   */
  async teamIdUsersMeMeetingsGetRaw(
    requestParameters: TeamIdUsersMeMeetingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserMeetingsResponse>> {
    const requestOptions = await this.teamIdUsersMeMeetingsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserMeetingsResponseFromJSON(jsonValue)
    );
  }

  /**
   * 현재 로그인된 사용자의 모임 목록을 조회합니다. 필터와 정렬 옵션을 지원합니다.
   * 내가 참여한/만든 모임 목록 조회
   */
  async teamIdUsersMeMeetingsGet(
    requestParameters: TeamIdUsersMeMeetingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserMeetingsResponse> {
    const response = await this.teamIdUsersMeMeetingsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdUsersMePatch without sending the request
   */
  async teamIdUsersMePatchRequestOpts(
    requestParameters: TeamIdUsersMePatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersMePatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/me`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
    };
  }

  /**
   * 현재 로그인된 사용자의 정보를 수정합니다. 변경할 필드만 전송하면 됩니다.
   * 내 정보 수정
   */
  async teamIdUsersMePatchRaw(
    requestParameters: TeamIdUsersMePatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const requestOptions = await this.teamIdUsersMePatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * 현재 로그인된 사용자의 정보를 수정합니다. 변경할 필드만 전송하면 됩니다.
   * 내 정보 수정
   */
  async teamIdUsersMePatch(
    requestParameters: TeamIdUsersMePatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.teamIdUsersMePatchRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdUsersMePostsGet without sending the request
   */
  async teamIdUsersMePostsGetRequestOpts(
    requestParameters: TeamIdUsersMePostsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersMePostsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/me/posts`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 로그인된 사용자가 작성한 게시글 목록을 조회합니다. 정렬 옵션을 지원합니다.
   * 내가 작성한 게시글 목록 조회
   */
  async teamIdUsersMePostsGetRaw(
    requestParameters: TeamIdUsersMePostsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserPostsResponse>> {
    const requestOptions = await this.teamIdUsersMePostsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserPostsResponseFromJSON(jsonValue)
    );
  }

  /**
   * 현재 로그인된 사용자가 작성한 게시글 목록을 조회합니다. 정렬 옵션을 지원합니다.
   * 내가 작성한 게시글 목록 조회
   */
  async teamIdUsersMePostsGet(
    requestParameters: TeamIdUsersMePostsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserPostsResponse> {
    const response = await this.teamIdUsersMePostsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdUsersMeReviewsGet without sending the request
   */
  async teamIdUsersMeReviewsGetRequestOpts(
    requestParameters: TeamIdUsersMeReviewsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersMeReviewsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/me/reviews`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 로그인된 사용자가 작성한 리뷰 목록을 조회합니다. 정렬 옵션을 지원합니다.
   * 내가 작성한 리뷰 목록 조회
   */
  async teamIdUsersMeReviewsGetRaw(
    requestParameters: TeamIdUsersMeReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserReviewsResponse>> {
    const requestOptions = await this.teamIdUsersMeReviewsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserReviewsResponseFromJSON(jsonValue)
    );
  }

  /**
   * 현재 로그인된 사용자가 작성한 리뷰 목록을 조회합니다. 정렬 옵션을 지원합니다.
   * 내가 작성한 리뷰 목록 조회
   */
  async teamIdUsersMeReviewsGet(
    requestParameters: TeamIdUsersMeReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserReviewsResponse> {
    const response = await this.teamIdUsersMeReviewsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdUsersUserIdGet without sending the request
   */
  async teamIdUsersUserIdGetRequestOpts(
    requestParameters: TeamIdUsersUserIdGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdUsersUserIdGet().'
      );
    }

    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling teamIdUsersUserIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/users/{userId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'userId'}}`,
      encodeURIComponent(String(requestParameters['userId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 사용자의 공개 프로필을 조회합니다. 인증 없이 접근 가능합니다.
   * 유저 프로필 조회
   */
  async teamIdUsersUserIdGetRaw(
    requestParameters: TeamIdUsersUserIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PublicUser>> {
    const requestOptions = await this.teamIdUsersUserIdGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PublicUserFromJSON(jsonValue));
  }

  /**
   * 특정 사용자의 공개 프로필을 조회합니다. 인증 없이 접근 가능합니다.
   * 유저 프로필 조회
   */
  async teamIdUsersUserIdGet(
    requestParameters: TeamIdUsersUserIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PublicUser> {
    const response = await this.teamIdUsersUserIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdUsersMeMeetingsGetTypeEnum = {
  Joined: 'joined',
  Created: 'created',
} as const;
export type TeamIdUsersMeMeetingsGetTypeEnum =
  (typeof TeamIdUsersMeMeetingsGetTypeEnum)[keyof typeof TeamIdUsersMeMeetingsGetTypeEnum];
/**
 * @export
 */
export const TeamIdUsersMeMeetingsGetCompletedEnum = {
  True: 'true',
  False: 'false',
} as const;
export type TeamIdUsersMeMeetingsGetCompletedEnum =
  (typeof TeamIdUsersMeMeetingsGetCompletedEnum)[keyof typeof TeamIdUsersMeMeetingsGetCompletedEnum];
/**
 * @export
 */
export const TeamIdUsersMeMeetingsGetReviewedEnum = {
  True: 'true',
  False: 'false',
} as const;
export type TeamIdUsersMeMeetingsGetReviewedEnum =
  (typeof TeamIdUsersMeMeetingsGetReviewedEnum)[keyof typeof TeamIdUsersMeMeetingsGetReviewedEnum];
/**
 * @export
 */
export const TeamIdUsersMeMeetingsGetSortByEnum = {
  DateTime: 'dateTime',
  JoinedAt: 'joinedAt',
  CreatedAt: 'createdAt',
} as const;
export type TeamIdUsersMeMeetingsGetSortByEnum =
  (typeof TeamIdUsersMeMeetingsGetSortByEnum)[keyof typeof TeamIdUsersMeMeetingsGetSortByEnum];
/**
 * @export
 */
export const TeamIdUsersMeMeetingsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdUsersMeMeetingsGetSortOrderEnum =
  (typeof TeamIdUsersMeMeetingsGetSortOrderEnum)[keyof typeof TeamIdUsersMeMeetingsGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdUsersMePostsGetSortByEnum = {
  CreatedAt: 'createdAt',
  ViewCount: 'viewCount',
  LikeCount: 'likeCount',
} as const;
export type TeamIdUsersMePostsGetSortByEnum =
  (typeof TeamIdUsersMePostsGetSortByEnum)[keyof typeof TeamIdUsersMePostsGetSortByEnum];
/**
 * @export
 */
export const TeamIdUsersMePostsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdUsersMePostsGetSortOrderEnum =
  (typeof TeamIdUsersMePostsGetSortOrderEnum)[keyof typeof TeamIdUsersMePostsGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdUsersMeReviewsGetSortByEnum = {
  CreatedAt: 'createdAt',
  Score: 'score',
} as const;
export type TeamIdUsersMeReviewsGetSortByEnum =
  (typeof TeamIdUsersMeReviewsGetSortByEnum)[keyof typeof TeamIdUsersMeReviewsGetSortByEnum];
/**
 * @export
 */
export const TeamIdUsersMeReviewsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdUsersMeReviewsGetSortOrderEnum =
  (typeof TeamIdUsersMeReviewsGetSortOrderEnum)[keyof typeof TeamIdUsersMeReviewsGetSortOrderEnum];
