/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthTokens
 */
export interface AuthTokens {
  /**
   *
   * @type {string}
   * @memberof AuthTokens
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof AuthTokens
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the AuthTokens interface.
 */
export function instanceOfAuthTokens(value: object): value is AuthTokens {
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
  return true;
}

export function AuthTokensFromJSON(json: any): AuthTokens {
  return AuthTokensFromJSONTyped(json, false);
}

export function AuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokens {
  if (json == null) {
    return json;
  }
  return {
    accessToken: json['accessToken'],
    refreshToken: json['refreshToken'],
  };
}

export function AuthTokensToJSON(json: any): AuthTokens {
  return AuthTokensToJSONTyped(json, false);
}

export function AuthTokensToJSONTyped(
  value?: AuthTokens | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    accessToken: value['accessToken'],
    refreshToken: value['refreshToken'],
  };
}
