/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CategoryStatisticsItem
 */
export interface CategoryStatisticsItem {
  /**
   *
   * @type {string}
   * @memberof CategoryStatisticsItem
   */
  type: string;
  /**
   *
   * @type {number}
   * @memberof CategoryStatisticsItem
   */
  averageScore: number;
  /**
   *
   * @type {number}
   * @memberof CategoryStatisticsItem
   */
  totalReviews: number;
}

/**
 * Check if a given object implements the CategoryStatisticsItem interface.
 */
export function instanceOfCategoryStatisticsItem(value: object): value is CategoryStatisticsItem {
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false;
  if (!('totalReviews' in value) || value['totalReviews'] === undefined) return false;
  return true;
}

export function CategoryStatisticsItemFromJSON(json: any): CategoryStatisticsItem {
  return CategoryStatisticsItemFromJSONTyped(json, false);
}

export function CategoryStatisticsItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CategoryStatisticsItem {
  if (json == null) {
    return json;
  }
  return {
    type: json['type'],
    averageScore: json['averageScore'],
    totalReviews: json['totalReviews'],
  };
}

export function CategoryStatisticsItemToJSON(json: any): CategoryStatisticsItem {
  return CategoryStatisticsItemToJSONTyped(json, false);
}

export function CategoryStatisticsItemToJSONTyped(
  value?: CategoryStatisticsItem | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value['type'],
    averageScore: value['averageScore'],
    totalReviews: value['totalReviews'],
  };
}
