/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Author } from './Author';
import { AuthorFromJSON, AuthorFromJSONTyped, AuthorToJSON, AuthorToJSONTyped } from './Author';

/**
 *
 * @export
 * @interface Comment
 */
export interface Comment {
  /**
   *
   * @type {number}
   * @memberof Comment
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof Comment
   */
  postId: number;
  /**
   *
   * @type {number}
   * @memberof Comment
   */
  authorId: number;
  /**
   *
   * @type {Author}
   * @memberof Comment
   */
  author: Author;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  content: string;
  /**
   *
   * @type {Date}
   * @memberof Comment
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Comment
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('postId' in value) || value['postId'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  if (!('author' in value) || value['author'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function CommentFromJSON(json: any): Comment {
  return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    postId: json['postId'],
    authorId: json['authorId'],
    author: AuthorFromJSON(json['author']),
    content: json['content'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function CommentToJSON(json: any): Comment {
  return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(
  value?: Comment | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    postId: value['postId'],
    authorId: value['authorId'],
    author: AuthorToJSON(value['author']),
    content: value['content'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
