/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CommentLike
 */
export interface CommentLike {
  /**
   *
   * @type {number}
   * @memberof CommentLike
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof CommentLike
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof CommentLike
   */
  commentId: number;
  /**
   *
   * @type {number}
   * @memberof CommentLike
   */
  userId: number;
  /**
   *
   * @type {Date}
   * @memberof CommentLike
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the CommentLike interface.
 */
export function instanceOfCommentLike(value: object): value is CommentLike {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('commentId' in value) || value['commentId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function CommentLikeFromJSON(json: any): CommentLike {
  return CommentLikeFromJSONTyped(json, false);
}

export function CommentLikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentLike {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    commentId: json['commentId'],
    userId: json['userId'],
    createdAt: new Date(json['createdAt']),
  };
}

export function CommentLikeToJSON(json: any): CommentLike {
  return CommentLikeToJSONTyped(json, false);
}

export function CommentLikeToJSONTyped(
  value?: CommentLike | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    commentId: value['commentId'],
    userId: value['userId'],
    createdAt: value['createdAt'].toISOString(),
  };
}
