/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailCheckRequest
 */
export interface EmailCheckRequest {
  /**
   *
   * @type {string}
   * @memberof EmailCheckRequest
   */
  email: string;
}

/**
 * Check if a given object implements the EmailCheckRequest interface.
 */
export function instanceOfEmailCheckRequest(value: object): value is EmailCheckRequest {
  if (!('email' in value) || value['email'] === undefined) return false;
  return true;
}

export function EmailCheckRequestFromJSON(json: any): EmailCheckRequest {
  return EmailCheckRequestFromJSONTyped(json, false);
}

export function EmailCheckRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EmailCheckRequest {
  if (json == null) {
    return json;
  }
  return {
    email: json['email'],
  };
}

export function EmailCheckRequestToJSON(json: any): EmailCheckRequest {
  return EmailCheckRequestToJSONTyped(json, false);
}

export function EmailCheckRequestToJSONTyped(
  value?: EmailCheckRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    email: value['email'],
  };
}
