/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailCheckResponse
 */
export interface EmailCheckResponse {
  /**
   *
   * @type {boolean}
   * @memberof EmailCheckResponse
   */
  available: boolean;
}

/**
 * Check if a given object implements the EmailCheckResponse interface.
 */
export function instanceOfEmailCheckResponse(value: object): value is EmailCheckResponse {
  if (!('available' in value) || value['available'] === undefined) return false;
  return true;
}

export function EmailCheckResponseFromJSON(json: any): EmailCheckResponse {
  return EmailCheckResponseFromJSONTyped(json, false);
}

export function EmailCheckResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EmailCheckResponse {
  if (json == null) {
    return json;
  }
  return {
    available: json['available'],
  };
}

export function EmailCheckResponseToJSON(json: any): EmailCheckResponse {
  return EmailCheckResponseToJSONTyped(json, false);
}

export function EmailCheckResponseToJSONTyped(
  value?: EmailCheckResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    available: value['available'],
  };
}
