/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavoriteWithMeeting } from './FavoriteWithMeeting';
import {
  FavoriteWithMeetingFromJSON,
  FavoriteWithMeetingFromJSONTyped,
  FavoriteWithMeetingToJSON,
  FavoriteWithMeetingToJSONTyped,
} from './FavoriteWithMeeting';

/**
 *
 * @export
 * @interface FavoriteList
 */
export interface FavoriteList {
  /**
   *
   * @type {Array<FavoriteWithMeeting>}
   * @memberof FavoriteList
   */
  data: Array<FavoriteWithMeeting>;
  /**
   *
   * @type {string}
   * @memberof FavoriteList
   */
  nextCursor?: string;
  /**
   *
   * @type {boolean}
   * @memberof FavoriteList
   */
  hasMore: boolean;
  /**
   *
   * @type {number}
   * @memberof FavoriteList
   */
  totalCount?: number;
  /**
   *
   * @type {number}
   * @memberof FavoriteList
   */
  currentOffset?: number;
  /**
   *
   * @type {number}
   * @memberof FavoriteList
   */
  limit?: number;
}

/**
 * Check if a given object implements the FavoriteList interface.
 */
export function instanceOfFavoriteList(value: object): value is FavoriteList {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function FavoriteListFromJSON(json: any): FavoriteList {
  return FavoriteListFromJSONTyped(json, false);
}

export function FavoriteListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FavoriteList {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(FavoriteWithMeetingFromJSON),
    nextCursor: json['nextCursor'] == null ? undefined : json['nextCursor'],
    hasMore: json['hasMore'],
    totalCount: json['totalCount'] == null ? undefined : json['totalCount'],
    currentOffset: json['currentOffset'] == null ? undefined : json['currentOffset'],
    limit: json['limit'] == null ? undefined : json['limit'],
  };
}

export function FavoriteListToJSON(json: any): FavoriteList {
  return FavoriteListToJSONTyped(json, false);
}

export function FavoriteListToJSONTyped(
  value?: FavoriteList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(FavoriteWithMeetingToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
    totalCount: value['totalCount'],
    currentOffset: value['currentOffset'],
    limit: value['limit'],
  };
}
