/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MeetingWithHost } from './MeetingWithHost';
import {
  MeetingWithHostFromJSON,
  MeetingWithHostFromJSONTyped,
  MeetingWithHostToJSON,
  MeetingWithHostToJSONTyped,
} from './MeetingWithHost';

/**
 *
 * @export
 * @interface FavoriteWithMeeting
 */
export interface FavoriteWithMeeting {
  /**
   *
   * @type {number}
   * @memberof FavoriteWithMeeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof FavoriteWithMeeting
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof FavoriteWithMeeting
   */
  meetingId: number;
  /**
   *
   * @type {number}
   * @memberof FavoriteWithMeeting
   */
  userId: number;
  /**
   *
   * @type {Date}
   * @memberof FavoriteWithMeeting
   */
  createdAt: Date;
  /**
   *
   * @type {MeetingWithHost}
   * @memberof FavoriteWithMeeting
   */
  meeting: MeetingWithHost;
}

/**
 * Check if a given object implements the FavoriteWithMeeting interface.
 */
export function instanceOfFavoriteWithMeeting(value: object): value is FavoriteWithMeeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('meetingId' in value) || value['meetingId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('meeting' in value) || value['meeting'] === undefined) return false;
  return true;
}

export function FavoriteWithMeetingFromJSON(json: any): FavoriteWithMeeting {
  return FavoriteWithMeetingFromJSONTyped(json, false);
}

export function FavoriteWithMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FavoriteWithMeeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    meetingId: json['meetingId'],
    userId: json['userId'],
    createdAt: new Date(json['createdAt']),
    meeting: MeetingWithHostFromJSON(json['meeting']),
  };
}

export function FavoriteWithMeetingToJSON(json: any): FavoriteWithMeeting {
  return FavoriteWithMeetingToJSONTyped(json, false);
}

export function FavoriteWithMeetingToJSONTyped(
  value?: FavoriteWithMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    meetingId: value['meetingId'],
    userId: value['userId'],
    createdAt: value['createdAt'].toISOString(),
    meeting: MeetingWithHostToJSON(value['meeting']),
  };
}
