/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import { UserFromJSON, UserFromJSONTyped, UserToJSON, UserToJSONTyped } from './User';

/**
 *
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
  /**
   *
   * @type {User}
   * @memberof LoginResponse
   */
  user: User;
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof LoginResponse
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
  if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
  return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
  return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
  if (json == null) {
    return json;
  }
  return {
    user: UserFromJSON(json['user']),
    accessToken: json['accessToken'],
    refreshToken: json['refreshToken'],
  };
}

export function LoginResponseToJSON(json: any): LoginResponse {
  return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(
  value?: LoginResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserToJSON(value['user']),
    accessToken: value['accessToken'],
    refreshToken: value['refreshToken'],
  };
}
