/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Meeting
 */
export interface Meeting {
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  region: string;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  address: string;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  latitude: number;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  longitude: number;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  dateTime: Date;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  registrationEnd: Date;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  capacity: number;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  participantCount: number;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  image: string;
  /**
   *
   * @type {string}
   * @memberof Meeting
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  canceledAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  confirmedAt: Date;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  hostId: number;
  /**
   *
   * @type {number}
   * @memberof Meeting
   */
  createdBy: number;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Meeting
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Meeting interface.
 */
export function instanceOfMeeting(value: object): value is Meeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('region' in value) || value['region'] === undefined) return false;
  if (!('address' in value) || value['address'] === undefined) return false;
  if (!('latitude' in value) || value['latitude'] === undefined) return false;
  if (!('longitude' in value) || value['longitude'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  if (!('registrationEnd' in value) || value['registrationEnd'] === undefined) return false;
  if (!('capacity' in value) || value['capacity'] === undefined) return false;
  if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('canceledAt' in value) || value['canceledAt'] === undefined) return false;
  if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
  if (!('hostId' in value) || value['hostId'] === undefined) return false;
  if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function MeetingFromJSON(json: any): Meeting {
  return MeetingFromJSONTyped(json, false);
}

export function MeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Meeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    name: json['name'],
    type: json['type'],
    region: json['region'],
    address: json['address'],
    latitude: json['latitude'],
    longitude: json['longitude'],
    dateTime: new Date(json['dateTime']),
    registrationEnd: new Date(json['registrationEnd']),
    capacity: json['capacity'],
    participantCount: json['participantCount'],
    image: json['image'],
    description: json['description'],
    canceledAt: new Date(json['canceledAt']),
    confirmedAt: new Date(json['confirmedAt']),
    hostId: json['hostId'],
    createdBy: json['createdBy'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function MeetingToJSON(json: any): Meeting {
  return MeetingToJSONTyped(json, false);
}

export function MeetingToJSONTyped(
  value?: Meeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    name: value['name'],
    type: value['type'],
    region: value['region'],
    address: value['address'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    dateTime: value['dateTime'].toISOString(),
    registrationEnd: value['registrationEnd'].toISOString(),
    capacity: value['capacity'],
    participantCount: value['participantCount'],
    image: value['image'],
    description: value['description'],
    canceledAt: value['canceledAt'].toISOString(),
    confirmedAt: value['confirmedAt'].toISOString(),
    hostId: value['hostId'],
    createdBy: value['createdBy'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
