/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NotificationData
 */
export interface NotificationData {
  /**
   *
   * @type {number}
   * @memberof NotificationData
   */
  meetingId?: number;
  /**
   *
   * @type {string}
   * @memberof NotificationData
   */
  meetingName?: string;
  /**
   *
   * @type {number}
   * @memberof NotificationData
   */
  postId?: number;
  /**
   *
   * @type {string}
   * @memberof NotificationData
   */
  postTitle?: string;
  /**
   *
   * @type {number}
   * @memberof NotificationData
   */
  commentId?: number;
  /**
   *
   * @type {string}
   * @memberof NotificationData
   */
  commentContent?: string;
  /**
   *
   * @type {string}
   * @memberof NotificationData
   */
  image?: string;
}

/**
 * Check if a given object implements the NotificationData interface.
 */
export function instanceOfNotificationData(value: object): value is NotificationData {
  return true;
}

export function NotificationDataFromJSON(json: any): NotificationData {
  return NotificationDataFromJSONTyped(json, false);
}

export function NotificationDataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): NotificationData {
  if (json == null) {
    return json;
  }
  return {
    meetingId: json['meetingId'] == null ? undefined : json['meetingId'],
    meetingName: json['meetingName'] == null ? undefined : json['meetingName'],
    postId: json['postId'] == null ? undefined : json['postId'],
    postTitle: json['postTitle'] == null ? undefined : json['postTitle'],
    commentId: json['commentId'] == null ? undefined : json['commentId'],
    commentContent: json['commentContent'] == null ? undefined : json['commentContent'],
    image: json['image'] == null ? undefined : json['image'],
  };
}

export function NotificationDataToJSON(json: any): NotificationData {
  return NotificationDataToJSONTyped(json, false);
}

export function NotificationDataToJSONTyped(
  value?: NotificationData | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    meetingId: value['meetingId'],
    meetingName: value['meetingName'],
    postId: value['postId'],
    postTitle: value['postTitle'],
    commentId: value['commentId'],
    commentContent: value['commentContent'],
    image: value['image'],
  };
}
