/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OAuthRequest
 */
export interface OAuthRequest {
  /**
   * OAuth 제공자의 access token
   * @type {string}
   * @memberof OAuthRequest
   */
  token: string;
}

/**
 * Check if a given object implements the OAuthRequest interface.
 */
export function instanceOfOAuthRequest(value: object): value is OAuthRequest {
  if (!('token' in value) || value['token'] === undefined) return false;
  return true;
}

export function OAuthRequestFromJSON(json: any): OAuthRequest {
  return OAuthRequestFromJSONTyped(json, false);
}

export function OAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthRequest {
  if (json == null) {
    return json;
  }
  return {
    token: json['token'],
  };
}

export function OAuthRequestToJSON(json: any): OAuthRequest {
  return OAuthRequestToJSONTyped(json, false);
}

export function OAuthRequestToJSONTyped(
  value?: OAuthRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value['token'],
  };
}
