/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OgMetadata
 */
export interface OgMetadata {
  /**
   *
   * @type {string}
   * @memberof OgMetadata
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof OgMetadata
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof OgMetadata
   */
  image: string;
  /**
   *
   * @type {string}
   * @memberof OgMetadata
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof OgMetadata
   */
  siteName: string;
}

/**
 * Check if a given object implements the OgMetadata interface.
 */
export function instanceOfOgMetadata(value: object): value is OgMetadata {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('url' in value) || value['url'] === undefined) return false;
  if (!('siteName' in value) || value['siteName'] === undefined) return false;
  return true;
}

export function OgMetadataFromJSON(json: any): OgMetadata {
  return OgMetadataFromJSONTyped(json, false);
}

export function OgMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OgMetadata {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    description: json['description'],
    image: json['image'],
    url: json['url'],
    siteName: json['siteName'],
  };
}

export function OgMetadataToJSON(json: any): OgMetadata {
  return OgMetadataToJSONTyped(json, false);
}

export function OgMetadataToJSONTyped(
  value?: OgMetadata | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    description: value['description'],
    image: value['image'],
    url: value['url'],
    siteName: value['siteName'],
  };
}
