/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewWithDetails } from './ReviewWithDetails';
import {
  ReviewWithDetailsFromJSON,
  ReviewWithDetailsFromJSONTyped,
  ReviewWithDetailsToJSON,
  ReviewWithDetailsToJSONTyped,
} from './ReviewWithDetails';

/**
 *
 * @export
 * @interface PaginatedReview
 */
export interface PaginatedReview {
  /**
   *
   * @type {Array<ReviewWithDetails>}
   * @memberof PaginatedReview
   */
  data: Array<ReviewWithDetails>;
  /**
   *
   * @type {string}
   * @memberof PaginatedReview
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof PaginatedReview
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the PaginatedReview interface.
 */
export function instanceOfPaginatedReview(value: object): value is PaginatedReview {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function PaginatedReviewFromJSON(json: any): PaginatedReview {
  return PaginatedReviewFromJSONTyped(json, false);
}

export function PaginatedReviewFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedReview {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(ReviewWithDetailsFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function PaginatedReviewToJSON(json: any): PaginatedReview {
  return PaginatedReviewToJSONTyped(json, false);
}

export function PaginatedReviewToJSONTyped(
  value?: PaginatedReview | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(ReviewWithDetailsToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
