/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Participant } from './Participant';
import {
  ParticipantFromJSON,
  ParticipantFromJSONTyped,
  ParticipantToJSON,
  ParticipantToJSONTyped,
} from './Participant';

/**
 *
 * @export
 * @interface ParticipantList
 */
export interface ParticipantList {
  /**
   *
   * @type {Array<Participant>}
   * @memberof ParticipantList
   */
  data: Array<Participant>;
  /**
   *
   * @type {string}
   * @memberof ParticipantList
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof ParticipantList
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the ParticipantList interface.
 */
export function instanceOfParticipantList(value: object): value is ParticipantList {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function ParticipantListFromJSON(json: any): ParticipantList {
  return ParticipantListFromJSONTyped(json, false);
}

export function ParticipantListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ParticipantList {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(ParticipantFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function ParticipantListToJSON(json: any): ParticipantList {
  return ParticipantListToJSONTyped(json, false);
}

export function ParticipantListToJSONTyped(
  value?: ParticipantList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(ParticipantToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
