/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
  CommentFromJSON,
  CommentFromJSONTyped,
  CommentToJSON,
  CommentToJSONTyped,
} from './Comment';
import type { PostWithAuthorAllOfCount } from './PostWithAuthorAllOfCount';
import {
  PostWithAuthorAllOfCountFromJSON,
  PostWithAuthorAllOfCountFromJSONTyped,
  PostWithAuthorAllOfCountToJSON,
  PostWithAuthorAllOfCountToJSONTyped,
} from './PostWithAuthorAllOfCount';
import type { PostWithCommentsAllOfAuthor } from './PostWithCommentsAllOfAuthor';
import {
  PostWithCommentsAllOfAuthorFromJSON,
  PostWithCommentsAllOfAuthorFromJSONTyped,
  PostWithCommentsAllOfAuthorToJSON,
  PostWithCommentsAllOfAuthorToJSONTyped,
} from './PostWithCommentsAllOfAuthor';

/**
 *
 * @export
 * @interface PostWithComments
 */
export interface PostWithComments {
  /**
   *
   * @type {number}
   * @memberof PostWithComments
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostWithComments
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof PostWithComments
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PostWithComments
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof PostWithComments
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof PostWithComments
   */
  authorId: number;
  /**
   *
   * @type {number}
   * @memberof PostWithComments
   */
  viewCount: number;
  /**
   *
   * @type {number}
   * @memberof PostWithComments
   */
  likeCount: number;
  /**
   *
   * @type {Date}
   * @memberof PostWithComments
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof PostWithComments
   */
  updatedAt: Date;
  /**
   *
   * @type {PostWithCommentsAllOfAuthor}
   * @memberof PostWithComments
   */
  author: PostWithCommentsAllOfAuthor;
  /**
   *
   * @type {PostWithAuthorAllOfCount}
   * @memberof PostWithComments
   */
  count: PostWithAuthorAllOfCount;
  /**
   *
   * @type {Array<Comment>}
   * @memberof PostWithComments
   */
  comments: Array<Comment>;
  /**
   *
   * @type {boolean}
   * @memberof PostWithComments
   */
  isLiked: boolean;
}

/**
 * Check if a given object implements the PostWithComments interface.
 */
export function instanceOfPostWithComments(value: object): value is PostWithComments {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
  if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('author' in value) || value['author'] === undefined) return false;
  if (!('count' in value) || value['count'] === undefined) return false;
  if (!('comments' in value) || value['comments'] === undefined) return false;
  if (!('isLiked' in value) || value['isLiked'] === undefined) return false;
  return true;
}

export function PostWithCommentsFromJSON(json: any): PostWithComments {
  return PostWithCommentsFromJSONTyped(json, false);
}

export function PostWithCommentsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostWithComments {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    title: json['title'],
    content: json['content'],
    image: json['image'],
    authorId: json['authorId'],
    viewCount: json['viewCount'],
    likeCount: json['likeCount'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    author: PostWithCommentsAllOfAuthorFromJSON(json['author']),
    count: PostWithAuthorAllOfCountFromJSON(json['_count']),
    comments: (json['comments'] as Array<any>).map(CommentFromJSON),
    isLiked: json['isLiked'],
  };
}

export function PostWithCommentsToJSON(json: any): PostWithComments {
  return PostWithCommentsToJSONTyped(json, false);
}

export function PostWithCommentsToJSONTyped(
  value?: PostWithComments | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    title: value['title'],
    content: value['content'],
    image: value['image'],
    authorId: value['authorId'],
    viewCount: value['viewCount'],
    likeCount: value['likeCount'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    author: PostWithCommentsAllOfAuthorToJSON(value['author']),
    _count: PostWithAuthorAllOfCountToJSON(value['count']),
    comments: (value['comments'] as Array<any>).map(CommentToJSON),
    isLiked: value['isLiked'],
  };
}
