/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostLike
 */
export interface PostLike {
  /**
   *
   * @type {number}
   * @memberof PostLike
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostLike
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof PostLike
   */
  postId: number;
  /**
   *
   * @type {number}
   * @memberof PostLike
   */
  userId: number;
  /**
   *
   * @type {Date}
   * @memberof PostLike
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the PostLike interface.
 */
export function instanceOfPostLike(value: object): value is PostLike {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('postId' in value) || value['postId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function PostLikeFromJSON(json: any): PostLike {
  return PostLikeFromJSONTyped(json, false);
}

export function PostLikeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostLike {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    postId: json['postId'],
    userId: json['userId'],
    createdAt: new Date(json['createdAt']),
  };
}

export function PostLikeToJSON(json: any): PostLike {
  return PostLikeToJSONTyped(json, false);
}

export function PostLikeToJSONTyped(
  value?: PostLike | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    postId: value['postId'],
    userId: value['userId'],
    createdAt: value['createdAt'].toISOString(),
  };
}
