/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostWithAuthor } from './PostWithAuthor';
import {
  PostWithAuthorFromJSON,
  PostWithAuthorFromJSONTyped,
  PostWithAuthorToJSON,
  PostWithAuthorToJSONTyped,
} from './PostWithAuthor';

/**
 *
 * @export
 * @interface PostList
 */
export interface PostList {
  /**
   *
   * @type {Array<PostWithAuthor>}
   * @memberof PostList
   */
  data: Array<PostWithAuthor>;
  /**
   *
   * @type {string}
   * @memberof PostList
   */
  nextCursor?: string;
  /**
   *
   * @type {boolean}
   * @memberof PostList
   */
  hasMore: boolean;
  /**
   *
   * @type {number}
   * @memberof PostList
   */
  totalCount?: number;
  /**
   *
   * @type {number}
   * @memberof PostList
   */
  currentOffset?: number;
  /**
   *
   * @type {number}
   * @memberof PostList
   */
  limit?: number;
  /**
   * 필터 조건에 맞는 게시글들의 조회수 합계
   * @type {number}
   * @memberof PostList
   */
  totalViewCount: number;
}

/**
 * Check if a given object implements the PostList interface.
 */
export function instanceOfPostList(value: object): value is PostList {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  if (!('totalViewCount' in value) || value['totalViewCount'] === undefined) return false;
  return true;
}

export function PostListFromJSON(json: any): PostList {
  return PostListFromJSONTyped(json, false);
}

export function PostListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostList {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(PostWithAuthorFromJSON),
    nextCursor: json['nextCursor'] == null ? undefined : json['nextCursor'],
    hasMore: json['hasMore'],
    totalCount: json['totalCount'] == null ? undefined : json['totalCount'],
    currentOffset: json['currentOffset'] == null ? undefined : json['currentOffset'],
    limit: json['limit'] == null ? undefined : json['limit'],
    totalViewCount: json['totalViewCount'],
  };
}

export function PostListToJSON(json: any): PostList {
  return PostListToJSONTyped(json, false);
}

export function PostListToJSONTyped(
  value?: PostList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(PostWithAuthorToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
    totalCount: value['totalCount'],
    currentOffset: value['currentOffset'],
    limit: value['limit'],
    totalViewCount: value['totalViewCount'],
  };
}
