/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostWithAuthorAllOfCount } from './PostWithAuthorAllOfCount';
import {
  PostWithAuthorAllOfCountFromJSON,
  PostWithAuthorAllOfCountFromJSONTyped,
  PostWithAuthorAllOfCountToJSON,
  PostWithAuthorAllOfCountToJSONTyped,
} from './PostWithAuthorAllOfCount';
import type { Author } from './Author';
import { AuthorFromJSON, AuthorFromJSONTyped, AuthorToJSON, AuthorToJSONTyped } from './Author';

/**
 *
 * @export
 * @interface PostWithAuthor
 */
export interface PostWithAuthor {
  /**
   *
   * @type {number}
   * @memberof PostWithAuthor
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PostWithAuthor
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof PostWithAuthor
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PostWithAuthor
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof PostWithAuthor
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof PostWithAuthor
   */
  authorId: number;
  /**
   *
   * @type {number}
   * @memberof PostWithAuthor
   */
  viewCount: number;
  /**
   *
   * @type {number}
   * @memberof PostWithAuthor
   */
  likeCount: number;
  /**
   *
   * @type {Date}
   * @memberof PostWithAuthor
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof PostWithAuthor
   */
  updatedAt: Date;
  /**
   *
   * @type {Author}
   * @memberof PostWithAuthor
   */
  author: Author;
  /**
   *
   * @type {PostWithAuthorAllOfCount}
   * @memberof PostWithAuthor
   */
  count: PostWithAuthorAllOfCount;
}

/**
 * Check if a given object implements the PostWithAuthor interface.
 */
export function instanceOfPostWithAuthor(value: object): value is PostWithAuthor {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  if (!('viewCount' in value) || value['viewCount'] === undefined) return false;
  if (!('likeCount' in value) || value['likeCount'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('author' in value) || value['author'] === undefined) return false;
  if (!('count' in value) || value['count'] === undefined) return false;
  return true;
}

export function PostWithAuthorFromJSON(json: any): PostWithAuthor {
  return PostWithAuthorFromJSONTyped(json, false);
}

export function PostWithAuthorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostWithAuthor {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    title: json['title'],
    content: json['content'],
    image: json['image'],
    authorId: json['authorId'],
    viewCount: json['viewCount'],
    likeCount: json['likeCount'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    author: AuthorFromJSON(json['author']),
    count: PostWithAuthorAllOfCountFromJSON(json['_count']),
  };
}

export function PostWithAuthorToJSON(json: any): PostWithAuthor {
  return PostWithAuthorToJSONTyped(json, false);
}

export function PostWithAuthorToJSONTyped(
  value?: PostWithAuthor | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    title: value['title'],
    content: value['content'],
    image: value['image'],
    authorId: value['authorId'],
    viewCount: value['viewCount'],
    likeCount: value['likeCount'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    author: AuthorToJSON(value['author']),
    _count: PostWithAuthorAllOfCountToJSON(value['count']),
  };
}
