/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostWithAuthorAllOfCount
 */
export interface PostWithAuthorAllOfCount {
  /**
   *
   * @type {number}
   * @memberof PostWithAuthorAllOfCount
   */
  comments: number;
}

/**
 * Check if a given object implements the PostWithAuthorAllOfCount interface.
 */
export function instanceOfPostWithAuthorAllOfCount(
  value: object
): value is PostWithAuthorAllOfCount {
  if (!('comments' in value) || value['comments'] === undefined) return false;
  return true;
}

export function PostWithAuthorAllOfCountFromJSON(json: any): PostWithAuthorAllOfCount {
  return PostWithAuthorAllOfCountFromJSONTyped(json, false);
}

export function PostWithAuthorAllOfCountFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PostWithAuthorAllOfCount {
  if (json == null) {
    return json;
  }
  return {
    comments: json['comments'],
  };
}

export function PostWithAuthorAllOfCountToJSON(json: any): PostWithAuthorAllOfCount {
  return PostWithAuthorAllOfCountToJSONTyped(json, false);
}

export function PostWithAuthorAllOfCountToJSONTyped(
  value?: PostWithAuthorAllOfCount | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    comments: value['comments'],
  };
}
