/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PresignedUrlRequest
 */
export interface PresignedUrlRequest {
  /**
   * 업로드할 파일명 (확장자 포함)
   * @type {string}
   * @memberof PresignedUrlRequest
   */
  fileName: string;
  /**
   * 이미지 MIME 타입
   * @type {PresignedUrlRequestContentTypeEnum}
   * @memberof PresignedUrlRequest
   */
  contentType: PresignedUrlRequestContentTypeEnum;
  /**
   * 이미지 저장 폴더
   * @type {PresignedUrlRequestFolderEnum}
   * @memberof PresignedUrlRequest
   */
  folder?: PresignedUrlRequestFolderEnum;
}

/**
 * @export
 */
export const PresignedUrlRequestContentTypeEnum = {
  ImageJpeg: 'image/jpeg',
  ImagePng: 'image/png',
  ImageWebp: 'image/webp',
  ImageGif: 'image/gif',
} as const;
export type PresignedUrlRequestContentTypeEnum =
  (typeof PresignedUrlRequestContentTypeEnum)[keyof typeof PresignedUrlRequestContentTypeEnum];

/**
 * @export
 */
export const PresignedUrlRequestFolderEnum = {
  Meetings: 'meetings',
  Users: 'users',
  Posts: 'posts',
} as const;
export type PresignedUrlRequestFolderEnum =
  (typeof PresignedUrlRequestFolderEnum)[keyof typeof PresignedUrlRequestFolderEnum];

/**
 * Check if a given object implements the PresignedUrlRequest interface.
 */
export function instanceOfPresignedUrlRequest(value: object): value is PresignedUrlRequest {
  if (!('fileName' in value) || value['fileName'] === undefined) return false;
  if (!('contentType' in value) || value['contentType'] === undefined) return false;
  return true;
}

export function PresignedUrlRequestFromJSON(json: any): PresignedUrlRequest {
  return PresignedUrlRequestFromJSONTyped(json, false);
}

export function PresignedUrlRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PresignedUrlRequest {
  if (json == null) {
    return json;
  }
  return {
    fileName: json['fileName'],
    contentType: json['contentType'],
    folder: json['folder'] == null ? undefined : json['folder'],
  };
}

export function PresignedUrlRequestToJSON(json: any): PresignedUrlRequest {
  return PresignedUrlRequestToJSONTyped(json, false);
}

export function PresignedUrlRequestToJSONTyped(
  value?: PresignedUrlRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    fileName: value['fileName'],
    contentType: value['contentType'],
    folder: value['folder'],
  };
}
