/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReviewWithDetailsAllOfUser } from './ReviewWithDetailsAllOfUser';
import {
  ReviewWithDetailsAllOfUserFromJSON,
  ReviewWithDetailsAllOfUserFromJSONTyped,
  ReviewWithDetailsAllOfUserToJSON,
  ReviewWithDetailsAllOfUserToJSONTyped,
} from './ReviewWithDetailsAllOfUser';
import type { ReviewWithDetailsAllOfMeeting } from './ReviewWithDetailsAllOfMeeting';
import {
  ReviewWithDetailsAllOfMeetingFromJSON,
  ReviewWithDetailsAllOfMeetingFromJSONTyped,
  ReviewWithDetailsAllOfMeetingToJSON,
  ReviewWithDetailsAllOfMeetingToJSONTyped,
} from './ReviewWithDetailsAllOfMeeting';

/**
 *
 * @export
 * @interface ReviewWithDetails
 */
export interface ReviewWithDetails {
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetails
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetails
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetails
   */
  meetingId: number;
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetails
   */
  userId: number;
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetails
   */
  score: number;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetails
   */
  comment: string;
  /**
   *
   * @type {Date}
   * @memberof ReviewWithDetails
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof ReviewWithDetails
   */
  updatedAt: Date;
  /**
   *
   * @type {ReviewWithDetailsAllOfUser}
   * @memberof ReviewWithDetails
   */
  user: ReviewWithDetailsAllOfUser;
  /**
   *
   * @type {ReviewWithDetailsAllOfMeeting}
   * @memberof ReviewWithDetails
   */
  meeting: ReviewWithDetailsAllOfMeeting;
}

/**
 * Check if a given object implements the ReviewWithDetails interface.
 */
export function instanceOfReviewWithDetails(value: object): value is ReviewWithDetails {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('meetingId' in value) || value['meetingId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('score' in value) || value['score'] === undefined) return false;
  if (!('comment' in value) || value['comment'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('meeting' in value) || value['meeting'] === undefined) return false;
  return true;
}

export function ReviewWithDetailsFromJSON(json: any): ReviewWithDetails {
  return ReviewWithDetailsFromJSONTyped(json, false);
}

export function ReviewWithDetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReviewWithDetails {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    meetingId: json['meetingId'],
    userId: json['userId'],
    score: json['score'],
    comment: json['comment'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    user: ReviewWithDetailsAllOfUserFromJSON(json['user']),
    meeting: ReviewWithDetailsAllOfMeetingFromJSON(json['meeting']),
  };
}

export function ReviewWithDetailsToJSON(json: any): ReviewWithDetails {
  return ReviewWithDetailsToJSONTyped(json, false);
}

export function ReviewWithDetailsToJSONTyped(
  value?: ReviewWithDetails | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    meetingId: value['meetingId'],
    userId: value['userId'],
    score: value['score'],
    comment: value['comment'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    user: ReviewWithDetailsAllOfUserToJSON(value['user']),
    meeting: ReviewWithDetailsAllOfMeetingToJSON(value['meeting']),
  };
}
