/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Review
 */
export interface Review {
  /**
   *
   * @type {number}
   * @memberof Review
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof Review
   */
  teamId: string;
  /**
   *
   * @type {number}
   * @memberof Review
   */
  meetingId: number;
  /**
   *
   * @type {number}
   * @memberof Review
   */
  userId: number;
  /**
   *
   * @type {number}
   * @memberof Review
   */
  score: number;
  /**
   *
   * @type {string}
   * @memberof Review
   */
  comment: string;
  /**
   *
   * @type {Date}
   * @memberof Review
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof Review
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('meetingId' in value) || value['meetingId'] === undefined) return false;
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('score' in value) || value['score'] === undefined) return false;
  if (!('comment' in value) || value['comment'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  return true;
}

export function ReviewFromJSON(json: any): Review {
  return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    meetingId: json['meetingId'],
    userId: json['userId'],
    score: json['score'],
    comment: json['comment'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  };
}

export function ReviewToJSON(json: any): Review {
  return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(
  value?: Review | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    meetingId: value['meetingId'],
    userId: value['userId'],
    score: value['score'],
    comment: value['comment'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  };
}
