/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReviewWithDetailsAllOfUser
 */
export interface ReviewWithDetailsAllOfUser {
  /**
   *
   * @type {number}
   * @memberof ReviewWithDetailsAllOfUser
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfUser
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfUser
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ReviewWithDetailsAllOfUser
   */
  image: string;
}

/**
 * Check if a given object implements the ReviewWithDetailsAllOfUser interface.
 */
export function instanceOfReviewWithDetailsAllOfUser(
  value: object
): value is ReviewWithDetailsAllOfUser {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  return true;
}

export function ReviewWithDetailsAllOfUserFromJSON(json: any): ReviewWithDetailsAllOfUser {
  return ReviewWithDetailsAllOfUserFromJSONTyped(json, false);
}

export function ReviewWithDetailsAllOfUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReviewWithDetailsAllOfUser {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    email: json['email'],
    name: json['name'],
    image: json['image'],
  };
}

export function ReviewWithDetailsAllOfUserToJSON(json: any): ReviewWithDetailsAllOfUser {
  return ReviewWithDetailsAllOfUserToJSONTyped(json, false);
}

export function ReviewWithDetailsAllOfUserToJSONTyped(
  value?: ReviewWithDetailsAllOfUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    email: value['email'],
    name: value['name'],
    image: value['image'],
  };
}
