/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TeamIdNotificationsDelete200Response
 */
export interface TeamIdNotificationsDelete200Response {
  /**
   *
   * @type {number}
   * @memberof TeamIdNotificationsDelete200Response
   */
  count: number;
}

/**
 * Check if a given object implements the TeamIdNotificationsDelete200Response interface.
 */
export function instanceOfTeamIdNotificationsDelete200Response(
  value: object
): value is TeamIdNotificationsDelete200Response {
  if (!('count' in value) || value['count'] === undefined) return false;
  return true;
}

export function TeamIdNotificationsDelete200ResponseFromJSON(
  json: any
): TeamIdNotificationsDelete200Response {
  return TeamIdNotificationsDelete200ResponseFromJSONTyped(json, false);
}

export function TeamIdNotificationsDelete200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TeamIdNotificationsDelete200Response {
  if (json == null) {
    return json;
  }
  return {
    count: json['count'],
  };
}

export function TeamIdNotificationsDelete200ResponseToJSON(
  json: any
): TeamIdNotificationsDelete200Response {
  return TeamIdNotificationsDelete200ResponseToJSONTyped(json, false);
}

export function TeamIdNotificationsDelete200ResponseToJSONTyped(
  value?: TeamIdNotificationsDelete200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value['count'],
  };
}
