/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMeetingStatus
 */
export interface UpdateMeetingStatus {
  /**
   * 변경할 상태 - CONFIRMED: 확정, CANCELED: 취소
   * @type {UpdateMeetingStatusStatusEnum}
   * @memberof UpdateMeetingStatus
   */
  status: UpdateMeetingStatusStatusEnum;
}

/**
 * @export
 */
export const UpdateMeetingStatusStatusEnum = {
  Confirmed: 'CONFIRMED',
  Canceled: 'CANCELED',
} as const;
export type UpdateMeetingStatusStatusEnum =
  (typeof UpdateMeetingStatusStatusEnum)[keyof typeof UpdateMeetingStatusStatusEnum];

/**
 * Check if a given object implements the UpdateMeetingStatus interface.
 */
export function instanceOfUpdateMeetingStatus(value: object): value is UpdateMeetingStatus {
  if (!('status' in value) || value['status'] === undefined) return false;
  return true;
}

export function UpdateMeetingStatusFromJSON(json: any): UpdateMeetingStatus {
  return UpdateMeetingStatusFromJSONTyped(json, false);
}

export function UpdateMeetingStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMeetingStatus {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'],
  };
}

export function UpdateMeetingStatusToJSON(json: any): UpdateMeetingStatus {
  return UpdateMeetingStatusToJSONTyped(json, false);
}

export function UpdateMeetingStatusToJSONTyped(
  value?: UpdateMeetingStatus | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
  };
}
