/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdatePost
 */
export interface UpdatePost {
  /**
   *
   * @type {string}
   * @memberof UpdatePost
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePost
   */
  content?: string;
  /**
   *
   * @type {string}
   * @memberof UpdatePost
   */
  image?: string;
}

/**
 * Check if a given object implements the UpdatePost interface.
 */
export function instanceOfUpdatePost(value: object): value is UpdatePost {
  return true;
}

export function UpdatePostFromJSON(json: any): UpdatePost {
  return UpdatePostFromJSONTyped(json, false);
}

export function UpdatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePost {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'] == null ? undefined : json['title'],
    content: json['content'] == null ? undefined : json['content'],
    image: json['image'] == null ? undefined : json['image'],
  };
}

export function UpdatePostToJSON(json: any): UpdatePost {
  return UpdatePostToJSONTyped(json, false);
}

export function UpdatePostToJSONTyped(
  value?: UpdatePost | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    content: value['content'],
    image: value['image'],
  };
}
