/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateReview
 */
export interface UpdateReview {
  /**
   *
   * @type {number}
   * @memberof UpdateReview
   */
  score?: number;
  /**
   *
   * @type {string}
   * @memberof UpdateReview
   */
  comment?: string;
}

/**
 * Check if a given object implements the UpdateReview interface.
 */
export function instanceOfUpdateReview(value: object): value is UpdateReview {
  return true;
}

export function UpdateReviewFromJSON(json: any): UpdateReview {
  return UpdateReviewFromJSONTyped(json, false);
}

export function UpdateReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReview {
  if (json == null) {
    return json;
  }
  return {
    score: json['score'] == null ? undefined : json['score'],
    comment: json['comment'] == null ? undefined : json['comment'],
  };
}

export function UpdateReviewToJSON(json: any): UpdateReview {
  return UpdateReviewToJSONTyped(json, false);
}

export function UpdateReviewToJSONTyped(
  value?: UpdateReview | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    score: value['score'],
    comment: value['comment'],
  };
}
