/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateMeetingType
 */
export interface UpdateMeetingType {
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingType
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingType
   */
  description?: string;
}

/**
 * Check if a given object implements the UpdateMeetingType interface.
 */
export function instanceOfUpdateMeetingType(value: object): value is UpdateMeetingType {
  return true;
}

export function UpdateMeetingTypeFromJSON(json: any): UpdateMeetingType {
  return UpdateMeetingTypeFromJSONTyped(json, false);
}

export function UpdateMeetingTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdateMeetingType {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function UpdateMeetingTypeToJSON(json: any): UpdateMeetingType {
  return UpdateMeetingTypeToJSONTyped(json, false);
}

export function UpdateMeetingTypeToJSONTyped(
  value?: UpdateMeetingType | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    description: value['description'],
  };
}
