/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserPostsResponseDataInnerAuthor
 */
export interface UserPostsResponseDataInnerAuthor {
  /**
   *
   * @type {number}
   * @memberof UserPostsResponseDataInnerAuthor
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInnerAuthor
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserPostsResponseDataInnerAuthor
   */
  image: string;
}

/**
 * Check if a given object implements the UserPostsResponseDataInnerAuthor interface.
 */
export function instanceOfUserPostsResponseDataInnerAuthor(
  value: object
): value is UserPostsResponseDataInnerAuthor {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  return true;
}

export function UserPostsResponseDataInnerAuthorFromJSON(
  json: any
): UserPostsResponseDataInnerAuthor {
  return UserPostsResponseDataInnerAuthorFromJSONTyped(json, false);
}

export function UserPostsResponseDataInnerAuthorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPostsResponseDataInnerAuthor {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    image: json['image'],
  };
}

export function UserPostsResponseDataInnerAuthorToJSON(
  json: any
): UserPostsResponseDataInnerAuthor {
  return UserPostsResponseDataInnerAuthorToJSONTyped(json, false);
}

export function UserPostsResponseDataInnerAuthorToJSONTyped(
  value?: UserPostsResponseDataInnerAuthor | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    image: value['image'],
  };
}
