/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Host } from './Host';
import { HostFromJSON, HostFromJSONTyped, HostToJSON, HostToJSONTyped } from './Host';

/**
 *
 * @export
 * @interface UserMeeting
 */
export interface UserMeeting {
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  teamId: string;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  type: string;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  region: string;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  address: string;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  latitude: number;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  longitude: number;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  dateTime: Date;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  registrationEnd: Date;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  capacity: number;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  participantCount: number;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  image: string;
  /**
   *
   * @type {string}
   * @memberof UserMeeting
   */
  description: string;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  canceledAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  confirmedAt: Date;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  hostId: number;
  /**
   *
   * @type {number}
   * @memberof UserMeeting
   */
  createdBy: number;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  updatedAt: Date;
  /**
   *
   * @type {Host}
   * @memberof UserMeeting
   */
  host: Host;
  /**
   * 로그인한 사용자의 찜 여부 (비로그인 시 미포함)
   * @type {boolean}
   * @memberof UserMeeting
   */
  isFavorited?: boolean;
  /**
   * 로그인한 사용자의 참여 여부 (비로그인 시 미포함)
   * @type {boolean}
   * @memberof UserMeeting
   */
  isJoined?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserMeeting
   */
  isCompleted: boolean;
  /**
   *
   * @type {Date}
   * @memberof UserMeeting
   */
  joinedAt: Date;
  /**
   *
   * @type {boolean}
   * @memberof UserMeeting
   */
  isReviewed: boolean;
  /**
   *
   * @type {UserMeetingRoleEnum}
   * @memberof UserMeeting
   */
  role: UserMeetingRoleEnum;
}

/**
 * @export
 */
export const UserMeetingRoleEnum = {
  Participant: 'participant',
  Host: 'host',
} as const;
export type UserMeetingRoleEnum = (typeof UserMeetingRoleEnum)[keyof typeof UserMeetingRoleEnum];

/**
 * Check if a given object implements the UserMeeting interface.
 */
export function instanceOfUserMeeting(value: object): value is UserMeeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('teamId' in value) || value['teamId'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('type' in value) || value['type'] === undefined) return false;
  if (!('region' in value) || value['region'] === undefined) return false;
  if (!('address' in value) || value['address'] === undefined) return false;
  if (!('latitude' in value) || value['latitude'] === undefined) return false;
  if (!('longitude' in value) || value['longitude'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  if (!('registrationEnd' in value) || value['registrationEnd'] === undefined) return false;
  if (!('capacity' in value) || value['capacity'] === undefined) return false;
  if (!('participantCount' in value) || value['participantCount'] === undefined) return false;
  if (!('image' in value) || value['image'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('canceledAt' in value) || value['canceledAt'] === undefined) return false;
  if (!('confirmedAt' in value) || value['confirmedAt'] === undefined) return false;
  if (!('hostId' in value) || value['hostId'] === undefined) return false;
  if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
  if (!('host' in value) || value['host'] === undefined) return false;
  if (!('isCompleted' in value) || value['isCompleted'] === undefined) return false;
  if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
  if (!('isReviewed' in value) || value['isReviewed'] === undefined) return false;
  if (!('role' in value) || value['role'] === undefined) return false;
  return true;
}

export function UserMeetingFromJSON(json: any): UserMeeting {
  return UserMeetingFromJSONTyped(json, false);
}

export function UserMeetingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMeeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    teamId: json['teamId'],
    name: json['name'],
    type: json['type'],
    region: json['region'],
    address: json['address'],
    latitude: json['latitude'],
    longitude: json['longitude'],
    dateTime: new Date(json['dateTime']),
    registrationEnd: new Date(json['registrationEnd']),
    capacity: json['capacity'],
    participantCount: json['participantCount'],
    image: json['image'],
    description: json['description'],
    canceledAt: new Date(json['canceledAt']),
    confirmedAt: new Date(json['confirmedAt']),
    hostId: json['hostId'],
    createdBy: json['createdBy'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
    host: HostFromJSON(json['host']),
    isFavorited: json['isFavorited'] == null ? undefined : json['isFavorited'],
    isJoined: json['isJoined'] == null ? undefined : json['isJoined'],
    isCompleted: json['isCompleted'],
    joinedAt: new Date(json['joinedAt']),
    isReviewed: json['isReviewed'],
    role: json['role'],
  };
}

export function UserMeetingToJSON(json: any): UserMeeting {
  return UserMeetingToJSONTyped(json, false);
}

export function UserMeetingToJSONTyped(
  value?: UserMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    teamId: value['teamId'],
    name: value['name'],
    type: value['type'],
    region: value['region'],
    address: value['address'],
    latitude: value['latitude'],
    longitude: value['longitude'],
    dateTime: value['dateTime'].toISOString(),
    registrationEnd: value['registrationEnd'].toISOString(),
    capacity: value['capacity'],
    participantCount: value['participantCount'],
    image: value['image'],
    description: value['description'],
    canceledAt: value['canceledAt'].toISOString(),
    confirmedAt: value['confirmedAt'].toISOString(),
    hostId: value['hostId'],
    createdBy: value['createdBy'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
    host: HostToJSON(value['host']),
    isFavorited: value['isFavorited'],
    isJoined: value['isJoined'],
    isCompleted: value['isCompleted'],
    joinedAt: value['joinedAt'].toISOString(),
    isReviewed: value['isReviewed'],
    role: value['role'],
  };
}
