/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserReviewMeeting } from './UserReviewMeeting';
import {
  UserReviewMeetingFromJSON,
  UserReviewMeetingFromJSONTyped,
  UserReviewMeetingToJSON,
  UserReviewMeetingToJSONTyped,
} from './UserReviewMeeting';

/**
 *
 * @export
 * @interface UserReview
 */
export interface UserReview {
  /**
   *
   * @type {number}
   * @memberof UserReview
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof UserReview
   */
  score: number;
  /**
   *
   * @type {string}
   * @memberof UserReview
   */
  comment: string;
  /**
   *
   * @type {number}
   * @memberof UserReview
   */
  meetingId: number;
  /**
   *
   * @type {UserReviewMeeting}
   * @memberof UserReview
   */
  meeting: UserReviewMeeting;
  /**
   *
   * @type {Date}
   * @memberof UserReview
   */
  createdAt: Date;
}

/**
 * Check if a given object implements the UserReview interface.
 */
export function instanceOfUserReview(value: object): value is UserReview {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('score' in value) || value['score'] === undefined) return false;
  if (!('comment' in value) || value['comment'] === undefined) return false;
  if (!('meetingId' in value) || value['meetingId'] === undefined) return false;
  if (!('meeting' in value) || value['meeting'] === undefined) return false;
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
  return true;
}

export function UserReviewFromJSON(json: any): UserReview {
  return UserReviewFromJSONTyped(json, false);
}

export function UserReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserReview {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    score: json['score'],
    comment: json['comment'],
    meetingId: json['meetingId'],
    meeting: UserReviewMeetingFromJSON(json['meeting']),
    createdAt: new Date(json['createdAt']),
  };
}

export function UserReviewToJSON(json: any): UserReview {
  return UserReviewToJSONTyped(json, false);
}

export function UserReviewToJSONTyped(
  value?: UserReview | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    score: value['score'],
    comment: value['comment'],
    meetingId: value['meetingId'],
    meeting: UserReviewMeetingToJSON(value['meeting']),
    createdAt: value['createdAt'].toISOString(),
  };
}
