/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserReview } from './UserReview';
import {
  UserReviewFromJSON,
  UserReviewFromJSONTyped,
  UserReviewToJSON,
  UserReviewToJSONTyped,
} from './UserReview';

/**
 *
 * @export
 * @interface UserReviewsResponse
 */
export interface UserReviewsResponse {
  /**
   *
   * @type {Array<UserReview>}
   * @memberof UserReviewsResponse
   */
  data: Array<UserReview>;
  /**
   *
   * @type {string}
   * @memberof UserReviewsResponse
   */
  nextCursor: string;
  /**
   *
   * @type {boolean}
   * @memberof UserReviewsResponse
   */
  hasMore: boolean;
}

/**
 * Check if a given object implements the UserReviewsResponse interface.
 */
export function instanceOfUserReviewsResponse(value: object): value is UserReviewsResponse {
  if (!('data' in value) || value['data'] === undefined) return false;
  if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
  if (!('hasMore' in value) || value['hasMore'] === undefined) return false;
  return true;
}

export function UserReviewsResponseFromJSON(json: any): UserReviewsResponse {
  return UserReviewsResponseFromJSONTyped(json, false);
}

export function UserReviewsResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserReviewsResponse {
  if (json == null) {
    return json;
  }
  return {
    data: (json['data'] as Array<any>).map(UserReviewFromJSON),
    nextCursor: json['nextCursor'],
    hasMore: json['hasMore'],
  };
}

export function UserReviewsResponseToJSON(json: any): UserReviewsResponse {
  return UserReviewsResponseToJSONTyped(json, false);
}

export function UserReviewsResponseToJSONTyped(
  value?: UserReviewsResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    data: (value['data'] as Array<any>).map(UserReviewToJSON),
    nextCursor: value['nextCursor'],
    hasMore: value['hasMore'],
  };
}
