/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserReviewMeeting
 */
export interface UserReviewMeeting {
  /**
   *
   * @type {number}
   * @memberof UserReviewMeeting
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof UserReviewMeeting
   */
  name: string;
  /**
   *
   * @type {Date}
   * @memberof UserReviewMeeting
   */
  dateTime: Date;
}

/**
 * Check if a given object implements the UserReviewMeeting interface.
 */
export function instanceOfUserReviewMeeting(value: object): value is UserReviewMeeting {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('dateTime' in value) || value['dateTime'] === undefined) return false;
  return true;
}

export function UserReviewMeetingFromJSON(json: any): UserReviewMeeting {
  return UserReviewMeetingFromJSONTyped(json, false);
}

export function UserReviewMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserReviewMeeting {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    dateTime: new Date(json['dateTime']),
  };
}

export function UserReviewMeetingToJSON(json: any): UserReviewMeeting {
  return UserReviewMeetingToJSONTyped(json, false);
}

export function UserReviewMeetingToJSONTyped(
  value?: UserReviewMeeting | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    dateTime: value['dateTime'].toISOString(),
  };
}
