/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AuthTokens,
  EmailCheckRequest,
  EmailCheckResponse,
  ErrorResponse,
  LoginRequest,
  LoginResponse,
  OAuthRequest,
  RefreshRequest,
  SignupRequest,
  User,
} from '../models/index';
import {
  AuthTokensFromJSON,
  AuthTokensToJSON,
  EmailCheckRequestFromJSON,
  EmailCheckRequestToJSON,
  EmailCheckResponseFromJSON,
  EmailCheckResponseToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
  OAuthRequestFromJSON,
  OAuthRequestToJSON,
  RefreshRequestFromJSON,
  RefreshRequestToJSON,
  SignupRequestFromJSON,
  SignupRequestToJSON,
  UserFromJSON,
  UserToJSON,
} from '../models/index';

export interface TeamIdAuthEmailCheckPostRequest {
  teamId: string;
  emailCheckRequest?: EmailCheckRequest;
}

export interface TeamIdAuthLoginPostRequest {
  teamId: string;
  loginRequest?: LoginRequest;
}

export interface TeamIdAuthLogoutPostRequest {
  teamId: string;
  refreshRequest?: RefreshRequest;
}

export interface TeamIdAuthRefreshPostRequest {
  teamId: string;
  refreshRequest?: RefreshRequest;
}

export interface TeamIdAuthSignupPostRequest {
  teamId: string;
  signupRequest?: SignupRequest;
}

export interface TeamIdOauthProviderPostRequest {
  teamId: string;
  provider: TeamIdOauthProviderPostProviderEnum;
  oAuthRequest?: OAuthRequest;
}

/**
 *
 */
export class AuthApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdAuthEmailCheckPost without sending the request
   */
  async teamIdAuthEmailCheckPostRequestOpts(
    requestParameters: TeamIdAuthEmailCheckPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthEmailCheckPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/email-check`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: EmailCheckRequestToJSON(requestParameters['emailCheckRequest']),
    };
  }

  /**
   * 회원가입 전에 팀 내 이메일 중복 여부를 확인합니다.
   * 이메일 사용 가능 여부 확인
   */
  async teamIdAuthEmailCheckPostRaw(
    requestParameters: TeamIdAuthEmailCheckPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<EmailCheckResponse>> {
    const requestOptions = await this.teamIdAuthEmailCheckPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EmailCheckResponseFromJSON(jsonValue)
    );
  }

  /**
   * 회원가입 전에 팀 내 이메일 중복 여부를 확인합니다.
   * 이메일 사용 가능 여부 확인
   */
  async teamIdAuthEmailCheckPost(
    requestParameters: TeamIdAuthEmailCheckPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<EmailCheckResponse> {
    const response = await this.teamIdAuthEmailCheckPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdAuthLoginPost without sending the request
   */
  async teamIdAuthLoginPostRequestOpts(
    requestParameters: TeamIdAuthLoginPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthLoginPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/login`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: LoginRequestToJSON(requestParameters['loginRequest']),
    };
  }

  /**
   * 이메일과 비밀번호로 로그인합니다. 성공 시 accessToken(15분)과 refreshToken(7일)을 발급합니다.
   * 로그인
   */
  async teamIdAuthLoginPostRaw(
    requestParameters: TeamIdAuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions = await this.teamIdAuthLoginPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
  }

  /**
   * 이메일과 비밀번호로 로그인합니다. 성공 시 accessToken(15분)과 refreshToken(7일)을 발급합니다.
   * 로그인
   */
  async teamIdAuthLoginPost(
    requestParameters: TeamIdAuthLoginPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.teamIdAuthLoginPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdAuthLogoutPost without sending the request
   */
  async teamIdAuthLogoutPostRequestOpts(
    requestParameters: TeamIdAuthLogoutPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthLogoutPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/logout`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RefreshRequestToJSON(requestParameters['refreshRequest']),
    };
  }

  /**
   * 현재 로그인된 세션을 종료합니다. 특정 리프레시 토큰만 무효화됩니다.
   * 로그아웃
   */
  async teamIdAuthLogoutPostRaw(
    requestParameters: TeamIdAuthLogoutPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions = await this.teamIdAuthLogoutPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   * 현재 로그인된 세션을 종료합니다. 특정 리프레시 토큰만 무효화됩니다.
   * 로그아웃
   */
  async teamIdAuthLogoutPost(
    requestParameters: TeamIdAuthLogoutPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.teamIdAuthLogoutPostRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for teamIdAuthRefreshPost without sending the request
   */
  async teamIdAuthRefreshPostRequestOpts(
    requestParameters: TeamIdAuthRefreshPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthRefreshPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/refresh`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: RefreshRequestToJSON(requestParameters['refreshRequest']),
    };
  }

  /**
   * 리프레시 토큰으로 새로운 accessToken과 refreshToken을 발급받습니다. 기존 리프레시 토큰은 무효화됩니다 (토큰 로테이션).  ⚠️ **프론트엔드 구현 주의사항**: 응답의 `refreshToken`이 `null`이면 기존에 저장된 refreshToken을 그대로 유지해야 합니다. `null`로 덮어쓰면 다음 갱신 시 실패합니다. 이는 동시 요청(예: axios interceptor에서 여러 401 동시 발생) 시 두 번째 요청부터 발생하며, 첫 번째 요청에서 이미 새 refreshToken을 받았으므로 그것을 유지하면 됩니다.
   * 토큰 갱신
   */
  async teamIdAuthRefreshPostRaw(
    requestParameters: TeamIdAuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<AuthTokens>> {
    const requestOptions = await this.teamIdAuthRefreshPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokensFromJSON(jsonValue));
  }

  /**
   * 리프레시 토큰으로 새로운 accessToken과 refreshToken을 발급받습니다. 기존 리프레시 토큰은 무효화됩니다 (토큰 로테이션).  ⚠️ **프론트엔드 구현 주의사항**: 응답의 `refreshToken`이 `null`이면 기존에 저장된 refreshToken을 그대로 유지해야 합니다. `null`로 덮어쓰면 다음 갱신 시 실패합니다. 이는 동시 요청(예: axios interceptor에서 여러 401 동시 발생) 시 두 번째 요청부터 발생하며, 첫 번째 요청에서 이미 새 refreshToken을 받았으므로 그것을 유지하면 됩니다.
   * 토큰 갱신
   */
  async teamIdAuthRefreshPost(
    requestParameters: TeamIdAuthRefreshPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<AuthTokens> {
    const response = await this.teamIdAuthRefreshPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdAuthSignupPost without sending the request
   */
  async teamIdAuthSignupPostRequestOpts(
    requestParameters: TeamIdAuthSignupPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdAuthSignupPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/auth/signup`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: SignupRequestToJSON(requestParameters['signupRequest']),
    };
  }

  /**
   * 새로운 사용자를 등록합니다. 이메일은 팀 내에서 고유해야 합니다.
   * 회원가입
   */
  async teamIdAuthSignupPostRaw(
    requestParameters: TeamIdAuthSignupPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<User>> {
    const requestOptions = await this.teamIdAuthSignupPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * 새로운 사용자를 등록합니다. 이메일은 팀 내에서 고유해야 합니다.
   * 회원가입
   */
  async teamIdAuthSignupPost(
    requestParameters: TeamIdAuthSignupPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<User> {
    const response = await this.teamIdAuthSignupPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdOauthProviderPost without sending the request
   */
  async teamIdOauthProviderPostRequestOpts(
    requestParameters: TeamIdOauthProviderPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdOauthProviderPost().'
      );
    }

    if (requestParameters['provider'] == null) {
      throw new runtime.RequiredError(
        'provider',
        'Required parameter "provider" was null or undefined when calling teamIdOauthProviderPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/oauth/{provider}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'provider'}}`,
      encodeURIComponent(String(requestParameters['provider']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: OAuthRequestToJSON(requestParameters['oAuthRequest']),
    };
  }

  /**
   * Google 또는 Kakao OAuth access token으로 로그인합니다. 최초 로그인 시 자동 가입되며, 기존 OAuth 계정이면 프로필을 업데이트합니다.
   * OAuth 로그인
   */
  async teamIdOauthProviderPostRaw(
    requestParameters: TeamIdOauthProviderPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    const requestOptions = await this.teamIdOauthProviderPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
  }

  /**
   * Google 또는 Kakao OAuth access token으로 로그인합니다. 최초 로그인 시 자동 가입되며, 기존 OAuth 계정이면 프로필을 업데이트합니다.
   * OAuth 로그인
   */
  async teamIdOauthProviderPost(
    requestParameters: TeamIdOauthProviderPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.teamIdOauthProviderPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdOauthProviderPostProviderEnum = {
  Google: 'google',
  Kakao: 'kakao',
} as const;
export type TeamIdOauthProviderPostProviderEnum =
  (typeof TeamIdOauthProviderPostProviderEnum)[keyof typeof TeamIdOauthProviderPostProviderEnum];
