/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ErrorResponse,
  FavoriteCount,
  FavoriteList,
  FavoriteWithMeeting,
  TeamIdMeetingsMeetingIdDelete200Response,
} from '../models/index';
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  FavoriteCountFromJSON,
  FavoriteCountToJSON,
  FavoriteListFromJSON,
  FavoriteListToJSON,
  FavoriteWithMeetingFromJSON,
  FavoriteWithMeetingToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
} from '../models/index';

export interface TeamIdFavoritesCountGetRequest {
  teamId: string;
}

export interface TeamIdFavoritesGetRequest {
  teamId: string;
  type?: string;
  region?: string;
  dateStart?: Date;
  dateEnd?: Date;
  sortBy?: TeamIdFavoritesGetSortByEnum;
  sortOrder?: TeamIdFavoritesGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsMeetingIdFavoritesDeleteRequest {
  teamId: string;
  meetingId: number;
}

export interface TeamIdMeetingsMeetingIdFavoritesPostRequest {
  teamId: string;
  meetingId: number;
}

/**
 *
 */
export class FavoritesApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdFavoritesCountGet without sending the request
   */
  async teamIdFavoritesCountGetRequestOpts(
    requestParameters: TeamIdFavoritesCountGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdFavoritesCountGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/favorites/count`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 사용자의 찜 개수를 조회합니다.
   * 찜 개수
   */
  async teamIdFavoritesCountGetRaw(
    requestParameters: TeamIdFavoritesCountGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FavoriteCount>> {
    const requestOptions = await this.teamIdFavoritesCountGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => FavoriteCountFromJSON(jsonValue));
  }

  /**
   * 현재 사용자의 찜 개수를 조회합니다.
   * 찜 개수
   */
  async teamIdFavoritesCountGet(
    requestParameters: TeamIdFavoritesCountGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FavoriteCount> {
    const response = await this.teamIdFavoritesCountGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdFavoritesGet without sending the request
   */
  async teamIdFavoritesGetRequestOpts(
    requestParameters: TeamIdFavoritesGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdFavoritesGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['region'] != null) {
      queryParameters['region'] = requestParameters['region'];
    }

    if (requestParameters['dateStart'] != null) {
      queryParameters['dateStart'] = (requestParameters['dateStart'] as any).toISOString();
    }

    if (requestParameters['dateEnd'] != null) {
      queryParameters['dateEnd'] = (requestParameters['dateEnd'] as any).toISOString();
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/favorites`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 찜한 모임 목록을 조회합니다.
   * 찜 목록
   */
  async teamIdFavoritesGetRaw(
    requestParameters: TeamIdFavoritesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FavoriteList>> {
    const requestOptions = await this.teamIdFavoritesGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => FavoriteListFromJSON(jsonValue));
  }

  /**
   * 찜한 모임 목록을 조회합니다.
   * 찜 목록
   */
  async teamIdFavoritesGet(
    requestParameters: TeamIdFavoritesGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FavoriteList> {
    const response = await this.teamIdFavoritesGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdFavoritesDelete without sending the request
   */
  async teamIdMeetingsMeetingIdFavoritesDeleteRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdFavoritesDelete().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdFavoritesDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/favorites`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 모임의 찜을 해제합니다.
   * 찜 해제 (중첩)
   */
  async teamIdMeetingsMeetingIdFavoritesDeleteRaw(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdFavoritesDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 특정 모임의 찜을 해제합니다.
   * 찜 해제 (중첩)
   */
  async teamIdMeetingsMeetingIdFavoritesDelete(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdMeetingsMeetingIdFavoritesDeleteRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdFavoritesPost without sending the request
   */
  async teamIdMeetingsMeetingIdFavoritesPostRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdFavoritesPost().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdFavoritesPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/favorites`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 모임을 찜합니다.
   * 찜 추가 (중첩)
   */
  async teamIdMeetingsMeetingIdFavoritesPostRaw(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<FavoriteWithMeeting>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdFavoritesPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FavoriteWithMeetingFromJSON(jsonValue)
    );
  }

  /**
   * 특정 모임을 찜합니다.
   * 찜 추가 (중첩)
   */
  async teamIdMeetingsMeetingIdFavoritesPost(
    requestParameters: TeamIdMeetingsMeetingIdFavoritesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<FavoriteWithMeeting> {
    const response = await this.teamIdMeetingsMeetingIdFavoritesPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdFavoritesGetSortByEnum = {
  CreatedAt: 'createdAt',
  DateTime: 'dateTime',
  RegistrationEnd: 'registrationEnd',
  ParticipantCount: 'participantCount',
} as const;
export type TeamIdFavoritesGetSortByEnum =
  (typeof TeamIdFavoritesGetSortByEnum)[keyof typeof TeamIdFavoritesGetSortByEnum];
/**
 * @export
 */
export const TeamIdFavoritesGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdFavoritesGetSortOrderEnum =
  (typeof TeamIdFavoritesGetSortOrderEnum)[keyof typeof TeamIdFavoritesGetSortOrderEnum];
