/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { PresignedUrlRequest, PresignedUrlResponse } from '../models/index';
import {
  PresignedUrlRequestFromJSON,
  PresignedUrlRequestToJSON,
  PresignedUrlResponseFromJSON,
  PresignedUrlResponseToJSON,
} from '../models/index';

export interface TeamIdImagesPostRequest {
  teamId: string;
  presignedUrlRequest?: PresignedUrlRequest;
}

/**
 *
 */
export class ImagesApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdImagesPost without sending the request
   */
  async teamIdImagesPostRequestOpts(
    requestParameters: TeamIdImagesPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdImagesPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/images`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: PresignedUrlRequestToJSON(requestParameters['presignedUrlRequest']),
    };
  }

  /**
   * S3 직접 업로드를 위한 presigned URL을 발급합니다.  **사용 흐름:** 1. 이 엔드포인트로 presigned URL 발급 2. 발급받은 presignedUrl로 PUT 요청 (body: 파일, Content-Type 헤더 필수) 3. publicUrl을 서버에 저장/표시용으로 사용  **지원 형식:** JPEG, PNG, WebP, GIF **URL 유효 시간:** 5분
   * 이미지 업로드 (Presigned URL 발급)
   */
  async teamIdImagesPostRaw(
    requestParameters: TeamIdImagesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PresignedUrlResponse>> {
    const requestOptions = await this.teamIdImagesPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PresignedUrlResponseFromJSON(jsonValue)
    );
  }

  /**
   * S3 직접 업로드를 위한 presigned URL을 발급합니다.  **사용 흐름:** 1. 이 엔드포인트로 presigned URL 발급 2. 발급받은 presignedUrl로 PUT 요청 (body: 파일, Content-Type 헤더 필수) 3. publicUrl을 서버에 저장/표시용으로 사용  **지원 형식:** JPEG, PNG, WebP, GIF **URL 유효 시간:** 5분
   * 이미지 업로드 (Presigned URL 발급)
   */
  async teamIdImagesPost(
    requestParameters: TeamIdImagesPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PresignedUrlResponse> {
    const response = await this.teamIdImagesPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
