/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CreateMeeting,
  ErrorResponse,
  JoinedMeetingList,
  MeetingList,
  MeetingWithHost,
  ParticipantList,
  TeamIdMeetingsMeetingIdDelete200Response,
  UpdateMeeting,
  UpdateMeetingStatus,
} from '../models/index';
import {
  CreateMeetingFromJSON,
  CreateMeetingToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  JoinedMeetingListFromJSON,
  JoinedMeetingListToJSON,
  MeetingListFromJSON,
  MeetingListToJSON,
  MeetingWithHostFromJSON,
  MeetingWithHostToJSON,
  ParticipantListFromJSON,
  ParticipantListToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
  UpdateMeetingFromJSON,
  UpdateMeetingToJSON,
  UpdateMeetingStatusFromJSON,
  UpdateMeetingStatusToJSON,
} from '../models/index';

export interface TeamIdMeetingsGetRequest {
  teamId: string;
  id?: number;
  type?: string;
  region?: string;
  date?: Date;
  createdBy?: number;
  sortBy?: TeamIdMeetingsGetSortByEnum;
  sortOrder?: TeamIdMeetingsGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsJoinedGetRequest {
  teamId: string;
  completed?: TeamIdMeetingsJoinedGetCompletedEnum;
  reviewed?: TeamIdMeetingsJoinedGetReviewedEnum;
  sortBy?: TeamIdMeetingsJoinedGetSortByEnum;
  sortOrder?: TeamIdMeetingsJoinedGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsMeetingIdDeleteRequest {
  teamId: string;
  meetingId: number;
}

export interface TeamIdMeetingsMeetingIdGetRequest {
  teamId: string;
  meetingId: number;
}

export interface TeamIdMeetingsMeetingIdJoinDeleteRequest {
  teamId: string;
  meetingId: number;
}

export interface TeamIdMeetingsMeetingIdJoinPostRequest {
  teamId: string;
  meetingId: number;
}

export interface TeamIdMeetingsMeetingIdParticipantsGetRequest {
  teamId: string;
  meetingId: number;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsMeetingIdPatchRequest {
  teamId: string;
  meetingId: number;
  updateMeeting?: UpdateMeeting;
}

export interface TeamIdMeetingsMeetingIdStatusPatchRequest {
  teamId: string;
  meetingId: number;
  updateMeetingStatus?: UpdateMeetingStatus;
}

export interface TeamIdMeetingsMyGetRequest {
  teamId: string;
  sortBy?: TeamIdMeetingsMyGetSortByEnum;
  sortOrder?: TeamIdMeetingsMyGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsPostRequest {
  teamId: string;
  createMeeting?: CreateMeeting;
}

/**
 *
 */
export class MeetingsApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdMeetingsGet without sending the request
   */
  async teamIdMeetingsGetRequestOpts(
    requestParameters: TeamIdMeetingsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['id'] != null) {
      queryParameters['id'] = requestParameters['id'];
    }

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['region'] != null) {
      queryParameters['region'] = requestParameters['region'];
    }

    if (requestParameters['date'] != null) {
      queryParameters['date'] = (requestParameters['date'] as any).toISOString();
    }

    if (requestParameters['createdBy'] != null) {
      queryParameters['createdBy'] = requestParameters['createdBy'];
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임 목록을 조회합니다. 취소되지 않은 모임만 반환됩니다.
   * 모임 목록
   */
  async teamIdMeetingsGetRaw(
    requestParameters: TeamIdMeetingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingList>> {
    const requestOptions = await this.teamIdMeetingsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingListFromJSON(jsonValue));
  }

  /**
   * 모임 목록을 조회합니다. 취소되지 않은 모임만 반환됩니다.
   * 모임 목록
   */
  async teamIdMeetingsGet(
    requestParameters: TeamIdMeetingsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingList> {
    const response = await this.teamIdMeetingsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsJoinedGet without sending the request
   */
  async teamIdMeetingsJoinedGetRequestOpts(
    requestParameters: TeamIdMeetingsJoinedGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsJoinedGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['completed'] != null) {
      queryParameters['completed'] = requestParameters['completed'];
    }

    if (requestParameters['reviewed'] != null) {
      queryParameters['reviewed'] = requestParameters['reviewed'];
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/joined`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 사용자가 참여한 모임 목록을 조회합니다.
   * 참여한 모임 목록
   */
  async teamIdMeetingsJoinedGetRaw(
    requestParameters: TeamIdMeetingsJoinedGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<JoinedMeetingList>> {
    const requestOptions = await this.teamIdMeetingsJoinedGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      JoinedMeetingListFromJSON(jsonValue)
    );
  }

  /**
   * 현재 사용자가 참여한 모임 목록을 조회합니다.
   * 참여한 모임 목록
   */
  async teamIdMeetingsJoinedGet(
    requestParameters: TeamIdMeetingsJoinedGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<JoinedMeetingList> {
    const response = await this.teamIdMeetingsJoinedGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdDelete without sending the request
   */
  async teamIdMeetingsMeetingIdDeleteRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdDelete().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임을 완전히 삭제합니다. 주최자만 가능합니다. 참가자, 리뷰, 찜이 모두 함께 삭제됩니다.
   * 모임 삭제
   */
  async teamIdMeetingsMeetingIdDeleteRaw(
    requestParameters: TeamIdMeetingsMeetingIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdMeetingsMeetingIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 모임을 완전히 삭제합니다. 주최자만 가능합니다. 참가자, 리뷰, 찜이 모두 함께 삭제됩니다.
   * 모임 삭제
   */
  async teamIdMeetingsMeetingIdDelete(
    requestParameters: TeamIdMeetingsMeetingIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdMeetingsMeetingIdDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdGet without sending the request
   */
  async teamIdMeetingsMeetingIdGetRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdGet().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 모임의 상세 정보를 조회합니다.
   * 모임 상세
   */
  async teamIdMeetingsMeetingIdGetRaw(
    requestParameters: TeamIdMeetingsMeetingIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingWithHost>> {
    const requestOptions = await this.teamIdMeetingsMeetingIdGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingWithHostFromJSON(jsonValue));
  }

  /**
   * 특정 모임의 상세 정보를 조회합니다.
   * 모임 상세
   */
  async teamIdMeetingsMeetingIdGet(
    requestParameters: TeamIdMeetingsMeetingIdGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingWithHost> {
    const response = await this.teamIdMeetingsMeetingIdGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdJoinDelete without sending the request
   */
  async teamIdMeetingsMeetingIdJoinDeleteRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdJoinDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdJoinDelete().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdJoinDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/join`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임 참여를 취소합니다.  - 호스트는 참여를 취소할 수 없습니다 (모임 취소를 이용해주세요) - 취소된 모임은 참여 취소 불가 - 이미 시작된 모임은 참여 취소 불가
   * 참여 취소
   */
  async teamIdMeetingsMeetingIdJoinDeleteRaw(
    requestParameters: TeamIdMeetingsMeetingIdJoinDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdJoinDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 모임 참여를 취소합니다.  - 호스트는 참여를 취소할 수 없습니다 (모임 취소를 이용해주세요) - 취소된 모임은 참여 취소 불가 - 이미 시작된 모임은 참여 취소 불가
   * 참여 취소
   */
  async teamIdMeetingsMeetingIdJoinDelete(
    requestParameters: TeamIdMeetingsMeetingIdJoinDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdMeetingsMeetingIdJoinDeleteRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdJoinPost without sending the request
   */
  async teamIdMeetingsMeetingIdJoinPostRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdJoinPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdJoinPost().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdJoinPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/join`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임에 참여 신청합니다.  **비즈니스 규칙:** - 취소된 모임은 참여 불가 (400 CANCELED) - 모집 마감일이 지나면 참여 불가 (400 REGISTRATION_CLOSED) - 정원 초과 시 참여 불가 (400 CAPACITY_FULL) - 동일 모임 중복 참여 불가 (409 ALREADY_JOINED) - 호스트는 자동 참여되므로 별도 신청 불필요  **알림:** - 참여 인원이 5명에 도달하면 호스트에게 개설 확정 알림 발생
   * 모임 참여
   */
  async teamIdMeetingsMeetingIdJoinPostRaw(
    requestParameters: TeamIdMeetingsMeetingIdJoinPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdMeetingsMeetingIdJoinPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 모임에 참여 신청합니다.  **비즈니스 규칙:** - 취소된 모임은 참여 불가 (400 CANCELED) - 모집 마감일이 지나면 참여 불가 (400 REGISTRATION_CLOSED) - 정원 초과 시 참여 불가 (400 CAPACITY_FULL) - 동일 모임 중복 참여 불가 (409 ALREADY_JOINED) - 호스트는 자동 참여되므로 별도 신청 불필요  **알림:** - 참여 인원이 5명에 도달하면 호스트에게 개설 확정 알림 발생
   * 모임 참여
   */
  async teamIdMeetingsMeetingIdJoinPost(
    requestParameters: TeamIdMeetingsMeetingIdJoinPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdMeetingsMeetingIdJoinPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdParticipantsGet without sending the request
   */
  async teamIdMeetingsMeetingIdParticipantsGetRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdParticipantsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdParticipantsGet().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdParticipantsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/participants`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임의 참가자 목록을 조회합니다.
   * 참가자 목록
   */
  async teamIdMeetingsMeetingIdParticipantsGetRaw(
    requestParameters: TeamIdMeetingsMeetingIdParticipantsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ParticipantList>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdParticipantsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => ParticipantListFromJSON(jsonValue));
  }

  /**
   * 모임의 참가자 목록을 조회합니다.
   * 참가자 목록
   */
  async teamIdMeetingsMeetingIdParticipantsGet(
    requestParameters: TeamIdMeetingsMeetingIdParticipantsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ParticipantList> {
    const response = await this.teamIdMeetingsMeetingIdParticipantsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdPatch without sending the request
   */
  async teamIdMeetingsMeetingIdPatchRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdPatch().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateMeetingToJSON(requestParameters['updateMeeting']),
    };
  }

  /**
   * 모임 정보를 수정합니다.  **비즈니스 규칙:** - 호스트만 수정할 수 있습니다 - 취소된 모임은 수정 불가 - 정원(capacity)을 현재 참가자 수보다 줄일 수 없습니다 - 모임 일시는 현재 시각 이후여야 합니다 - 모집 마감일은 모임 일시 이전이어야 합니다
   * 모임 수정
   */
  async teamIdMeetingsMeetingIdPatchRaw(
    requestParameters: TeamIdMeetingsMeetingIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingWithHost>> {
    const requestOptions = await this.teamIdMeetingsMeetingIdPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingWithHostFromJSON(jsonValue));
  }

  /**
   * 모임 정보를 수정합니다.  **비즈니스 규칙:** - 호스트만 수정할 수 있습니다 - 취소된 모임은 수정 불가 - 정원(capacity)을 현재 참가자 수보다 줄일 수 없습니다 - 모임 일시는 현재 시각 이후여야 합니다 - 모집 마감일은 모임 일시 이전이어야 합니다
   * 모임 수정
   */
  async teamIdMeetingsMeetingIdPatch(
    requestParameters: TeamIdMeetingsMeetingIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingWithHost> {
    const response = await this.teamIdMeetingsMeetingIdPatchRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdStatusPatch without sending the request
   */
  async teamIdMeetingsMeetingIdStatusPatchRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdStatusPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdStatusPatch().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdStatusPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/status`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateMeetingStatusToJSON(requestParameters['updateMeetingStatus']),
    };
  }

  /**
   * 모임을 확정하거나 취소합니다. 주최자만 가능합니다.
   * 모임 상태 변경
   */
  async teamIdMeetingsMeetingIdStatusPatchRaw(
    requestParameters: TeamIdMeetingsMeetingIdStatusPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingWithHost>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdStatusPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingWithHostFromJSON(jsonValue));
  }

  /**
   * 모임을 확정하거나 취소합니다. 주최자만 가능합니다.
   * 모임 상태 변경
   */
  async teamIdMeetingsMeetingIdStatusPatch(
    requestParameters: TeamIdMeetingsMeetingIdStatusPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingWithHost> {
    const response = await this.teamIdMeetingsMeetingIdStatusPatchRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMyGet without sending the request
   */
  async teamIdMeetingsMyGetRequestOpts(
    requestParameters: TeamIdMeetingsMyGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMyGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/my`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 현재 사용자가 호스트인 모임 목록을 조회합니다.
   * 내가 만든 모임 목록
   */
  async teamIdMeetingsMyGetRaw(
    requestParameters: TeamIdMeetingsMyGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingList>> {
    const requestOptions = await this.teamIdMeetingsMyGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingListFromJSON(jsonValue));
  }

  /**
   * 현재 사용자가 호스트인 모임 목록을 조회합니다.
   * 내가 만든 모임 목록
   */
  async teamIdMeetingsMyGet(
    requestParameters: TeamIdMeetingsMyGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingList> {
    const response = await this.teamIdMeetingsMyGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsPost without sending the request
   */
  async teamIdMeetingsPostRequestOpts(
    requestParameters: TeamIdMeetingsPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateMeetingToJSON(requestParameters['createMeeting']),
    };
  }

  /**
   * 새로운 모임을 생성합니다.  **비즈니스 규칙:** - 모임 일시(dateTime)는 현재 시각 이후여야 합니다 - 모집 마감일(registrationEnd)은 모임 일시 이전이어야 합니다 - 호스트는 자동으로 첫 번째 참가자로 등록됩니다 - capacity는 최소 1명 이상이어야 합니다
   * 모임 생성
   */
  async teamIdMeetingsPostRaw(
    requestParameters: TeamIdMeetingsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<MeetingWithHost>> {
    const requestOptions = await this.teamIdMeetingsPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => MeetingWithHostFromJSON(jsonValue));
  }

  /**
   * 새로운 모임을 생성합니다.  **비즈니스 규칙:** - 모임 일시(dateTime)는 현재 시각 이후여야 합니다 - 모집 마감일(registrationEnd)은 모임 일시 이전이어야 합니다 - 호스트는 자동으로 첫 번째 참가자로 등록됩니다 - capacity는 최소 1명 이상이어야 합니다
   * 모임 생성
   */
  async teamIdMeetingsPost(
    requestParameters: TeamIdMeetingsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<MeetingWithHost> {
    const response = await this.teamIdMeetingsPostRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdMeetingsGetSortByEnum = {
  DateTime: 'dateTime',
  RegistrationEnd: 'registrationEnd',
  ParticipantCount: 'participantCount',
} as const;
export type TeamIdMeetingsGetSortByEnum =
  (typeof TeamIdMeetingsGetSortByEnum)[keyof typeof TeamIdMeetingsGetSortByEnum];
/**
 * @export
 */
export const TeamIdMeetingsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdMeetingsGetSortOrderEnum =
  (typeof TeamIdMeetingsGetSortOrderEnum)[keyof typeof TeamIdMeetingsGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdMeetingsJoinedGetCompletedEnum = {
  True: 'true',
  False: 'false',
} as const;
export type TeamIdMeetingsJoinedGetCompletedEnum =
  (typeof TeamIdMeetingsJoinedGetCompletedEnum)[keyof typeof TeamIdMeetingsJoinedGetCompletedEnum];
/**
 * @export
 */
export const TeamIdMeetingsJoinedGetReviewedEnum = {
  True: 'true',
  False: 'false',
} as const;
export type TeamIdMeetingsJoinedGetReviewedEnum =
  (typeof TeamIdMeetingsJoinedGetReviewedEnum)[keyof typeof TeamIdMeetingsJoinedGetReviewedEnum];
/**
 * @export
 */
export const TeamIdMeetingsJoinedGetSortByEnum = {
  DateTime: 'dateTime',
  RegistrationEnd: 'registrationEnd',
  JoinedAt: 'joinedAt',
} as const;
export type TeamIdMeetingsJoinedGetSortByEnum =
  (typeof TeamIdMeetingsJoinedGetSortByEnum)[keyof typeof TeamIdMeetingsJoinedGetSortByEnum];
/**
 * @export
 */
export const TeamIdMeetingsJoinedGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdMeetingsJoinedGetSortOrderEnum =
  (typeof TeamIdMeetingsJoinedGetSortOrderEnum)[keyof typeof TeamIdMeetingsJoinedGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdMeetingsMyGetSortByEnum = {
  DateTime: 'dateTime',
  RegistrationEnd: 'registrationEnd',
  ParticipantCount: 'participantCount',
} as const;
export type TeamIdMeetingsMyGetSortByEnum =
  (typeof TeamIdMeetingsMyGetSortByEnum)[keyof typeof TeamIdMeetingsMyGetSortByEnum];
/**
 * @export
 */
export const TeamIdMeetingsMyGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdMeetingsMyGetSortOrderEnum =
  (typeof TeamIdMeetingsMyGetSortOrderEnum)[keyof typeof TeamIdMeetingsMyGetSortOrderEnum];
