/* tslint:disable */
/* eslint-disable */
/**
 * 같이 달램 API
 * 모임 매칭 플랫폼 API  ## 인증 방식 - **JWT Bearer Token**: 로그인 후 발급받은 accessToken을 Authorization 헤더에 포함 - accessToken 만료 시간: 15분 - refreshToken 만료 시간: 7일  ## 사용 예시 ``` Authorization: Bearer eyJhbGciOiJIUzI1NiIs... ```
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CategoryStatisticsItem,
  CreateReviewByMeeting,
  ErrorResponse,
  PaginatedReview,
  ReviewStatistics,
  ReviewWithDetails,
  TeamIdMeetingsMeetingIdDelete200Response,
  UpdateReview,
} from '../models/index';
import {
  CategoryStatisticsItemFromJSON,
  CategoryStatisticsItemToJSON,
  CreateReviewByMeetingFromJSON,
  CreateReviewByMeetingToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  PaginatedReviewFromJSON,
  PaginatedReviewToJSON,
  ReviewStatisticsFromJSON,
  ReviewStatisticsToJSON,
  ReviewWithDetailsFromJSON,
  ReviewWithDetailsToJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseFromJSON,
  TeamIdMeetingsMeetingIdDelete200ResponseToJSON,
  UpdateReviewFromJSON,
  UpdateReviewToJSON,
} from '../models/index';

export interface TeamIdMeetingsMeetingIdReviewsGetRequest {
  teamId: string;
  meetingId: number;
  userId?: number;
  type?: string;
  region?: string;
  dateStart?: Date;
  dateEnd?: Date;
  registrationEndStart?: Date;
  registrationEndEnd?: Date;
  sortBy?: TeamIdMeetingsMeetingIdReviewsGetSortByEnum;
  sortOrder?: TeamIdMeetingsMeetingIdReviewsGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdMeetingsMeetingIdReviewsPostRequest {
  teamId: string;
  meetingId: number;
  createReviewByMeeting?: CreateReviewByMeeting;
}

export interface TeamIdReviewsCategoriesStatisticsGetRequest {
  teamId: string;
}

export interface TeamIdReviewsGetRequest {
  teamId: string;
  meetingId?: number;
  userId?: number;
  type?: string;
  region?: string;
  dateStart?: Date;
  dateEnd?: Date;
  registrationEndStart?: Date;
  registrationEndEnd?: Date;
  sortBy?: TeamIdReviewsGetSortByEnum;
  sortOrder?: TeamIdReviewsGetSortOrderEnum;
  cursor?: string;
  size?: number;
}

export interface TeamIdReviewsReviewIdDeleteRequest {
  teamId: string;
  reviewId: number;
}

export interface TeamIdReviewsReviewIdPatchRequest {
  teamId: string;
  reviewId: number;
  updateReview?: UpdateReview;
}

export interface TeamIdReviewsStatisticsGetRequest {
  teamId: string;
}

/**
 *
 */
export class ReviewsApi extends runtime.BaseAPI {
  /**
   * Creates request options for teamIdMeetingsMeetingIdReviewsGet without sending the request
   */
  async teamIdMeetingsMeetingIdReviewsGetRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdReviewsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdReviewsGet().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdReviewsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['userId'] != null) {
      queryParameters['userId'] = requestParameters['userId'];
    }

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['region'] != null) {
      queryParameters['region'] = requestParameters['region'];
    }

    if (requestParameters['dateStart'] != null) {
      queryParameters['dateStart'] = (requestParameters['dateStart'] as any).toISOString();
    }

    if (requestParameters['dateEnd'] != null) {
      queryParameters['dateEnd'] = (requestParameters['dateEnd'] as any).toISOString();
    }

    if (requestParameters['registrationEndStart'] != null) {
      queryParameters['registrationEndStart'] = (
        requestParameters['registrationEndStart'] as any
      ).toISOString();
    }

    if (requestParameters['registrationEndEnd'] != null) {
      queryParameters['registrationEndEnd'] = (
        requestParameters['registrationEndEnd'] as any
      ).toISOString();
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/reviews`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 특정 모임의 리뷰 목록을 조회합니다.
   * 특정 모임 리뷰 목록 (중첩)
   */
  async teamIdMeetingsMeetingIdReviewsGetRaw(
    requestParameters: TeamIdMeetingsMeetingIdReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PaginatedReview>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdReviewsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedReviewFromJSON(jsonValue));
  }

  /**
   * 특정 모임의 리뷰 목록을 조회합니다.
   * 특정 모임 리뷰 목록 (중첩)
   */
  async teamIdMeetingsMeetingIdReviewsGet(
    requestParameters: TeamIdMeetingsMeetingIdReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PaginatedReview> {
    const response = await this.teamIdMeetingsMeetingIdReviewsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdMeetingsMeetingIdReviewsPost without sending the request
   */
  async teamIdMeetingsMeetingIdReviewsPostRequestOpts(
    requestParameters: TeamIdMeetingsMeetingIdReviewsPostRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdMeetingsMeetingIdReviewsPost().'
      );
    }

    if (requestParameters['meetingId'] == null) {
      throw new runtime.RequiredError(
        'meetingId',
        'Required parameter "meetingId" was null or undefined when calling teamIdMeetingsMeetingIdReviewsPost().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/meetings/{meetingId}/reviews`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'meetingId'}}`,
      encodeURIComponent(String(requestParameters['meetingId']))
    );

    return {
      path: urlPath,
      method: 'POST',
      headers: headerParameters,
      query: queryParameters,
      body: CreateReviewByMeetingToJSON(requestParameters['createReviewByMeeting']),
    };
  }

  /**
   * 특정 모임에 리뷰를 작성합니다.
   * 리뷰 작성
   */
  async teamIdMeetingsMeetingIdReviewsPostRaw(
    requestParameters: TeamIdMeetingsMeetingIdReviewsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ReviewWithDetails>> {
    const requestOptions =
      await this.teamIdMeetingsMeetingIdReviewsPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ReviewWithDetailsFromJSON(jsonValue)
    );
  }

  /**
   * 특정 모임에 리뷰를 작성합니다.
   * 리뷰 작성
   */
  async teamIdMeetingsMeetingIdReviewsPost(
    requestParameters: TeamIdMeetingsMeetingIdReviewsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ReviewWithDetails> {
    const response = await this.teamIdMeetingsMeetingIdReviewsPostRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdReviewsCategoriesStatisticsGet without sending the request
   */
  async teamIdReviewsCategoriesStatisticsGetRequestOpts(
    requestParameters: TeamIdReviewsCategoriesStatisticsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdReviewsCategoriesStatisticsGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/reviews/categories/statistics`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 모임 종류별 리뷰 통계를 조회합니다.
   * 카테고리별 리뷰 통계
   */
  async teamIdReviewsCategoriesStatisticsGetRaw(
    requestParameters: TeamIdReviewsCategoriesStatisticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<CategoryStatisticsItem>>> {
    const requestOptions =
      await this.teamIdReviewsCategoriesStatisticsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(CategoryStatisticsItemFromJSON)
    );
  }

  /**
   * 모임 종류별 리뷰 통계를 조회합니다.
   * 카테고리별 리뷰 통계
   */
  async teamIdReviewsCategoriesStatisticsGet(
    requestParameters: TeamIdReviewsCategoriesStatisticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<CategoryStatisticsItem>> {
    const response = await this.teamIdReviewsCategoriesStatisticsGetRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Creates request options for teamIdReviewsGet without sending the request
   */
  async teamIdReviewsGetRequestOpts(
    requestParameters: TeamIdReviewsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdReviewsGet().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['meetingId'] != null) {
      queryParameters['meetingId'] = requestParameters['meetingId'];
    }

    if (requestParameters['userId'] != null) {
      queryParameters['userId'] = requestParameters['userId'];
    }

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    if (requestParameters['region'] != null) {
      queryParameters['region'] = requestParameters['region'];
    }

    if (requestParameters['dateStart'] != null) {
      queryParameters['dateStart'] = (requestParameters['dateStart'] as any).toISOString();
    }

    if (requestParameters['dateEnd'] != null) {
      queryParameters['dateEnd'] = (requestParameters['dateEnd'] as any).toISOString();
    }

    if (requestParameters['registrationEndStart'] != null) {
      queryParameters['registrationEndStart'] = (
        requestParameters['registrationEndStart'] as any
      ).toISOString();
    }

    if (requestParameters['registrationEndEnd'] != null) {
      queryParameters['registrationEndEnd'] = (
        requestParameters['registrationEndEnd'] as any
      ).toISOString();
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sortBy'] = requestParameters['sortBy'];
    }

    if (requestParameters['sortOrder'] != null) {
      queryParameters['sortOrder'] = requestParameters['sortOrder'];
    }

    if (requestParameters['cursor'] != null) {
      queryParameters['cursor'] = requestParameters['cursor'];
    }

    if (requestParameters['size'] != null) {
      queryParameters['size'] = requestParameters['size'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/reviews`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 리뷰 목록을 조회합니다.
   * 리뷰 목록
   */
  async teamIdReviewsGetRaw(
    requestParameters: TeamIdReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<PaginatedReview>> {
    const requestOptions = await this.teamIdReviewsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedReviewFromJSON(jsonValue));
  }

  /**
   * 리뷰 목록을 조회합니다.
   * 리뷰 목록
   */
  async teamIdReviewsGet(
    requestParameters: TeamIdReviewsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<PaginatedReview> {
    const response = await this.teamIdReviewsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdReviewsReviewIdDelete without sending the request
   */
  async teamIdReviewsReviewIdDeleteRequestOpts(
    requestParameters: TeamIdReviewsReviewIdDeleteRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdReviewsReviewIdDelete().'
      );
    }

    if (requestParameters['reviewId'] == null) {
      throw new runtime.RequiredError(
        'reviewId',
        'Required parameter "reviewId" was null or undefined when calling teamIdReviewsReviewIdDelete().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/reviews/{reviewId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'reviewId'}}`,
      encodeURIComponent(String(requestParameters['reviewId']))
    );

    return {
      path: urlPath,
      method: 'DELETE',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 리뷰를 삭제합니다. 본인의 리뷰만 삭제할 수 있습니다.
   * 리뷰 삭제
   */
  async teamIdReviewsReviewIdDeleteRaw(
    requestParameters: TeamIdReviewsReviewIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<TeamIdMeetingsMeetingIdDelete200Response>> {
    const requestOptions = await this.teamIdReviewsReviewIdDeleteRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TeamIdMeetingsMeetingIdDelete200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * 리뷰를 삭제합니다. 본인의 리뷰만 삭제할 수 있습니다.
   * 리뷰 삭제
   */
  async teamIdReviewsReviewIdDelete(
    requestParameters: TeamIdReviewsReviewIdDeleteRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<TeamIdMeetingsMeetingIdDelete200Response> {
    const response = await this.teamIdReviewsReviewIdDeleteRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdReviewsReviewIdPatch without sending the request
   */
  async teamIdReviewsReviewIdPatchRequestOpts(
    requestParameters: TeamIdReviewsReviewIdPatchRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdReviewsReviewIdPatch().'
      );
    }

    if (requestParameters['reviewId'] == null) {
      throw new runtime.RequiredError(
        'reviewId',
        'Required parameter "reviewId" was null or undefined when calling teamIdReviewsReviewIdPatch().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/reviews/{reviewId}`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );
    urlPath = urlPath.replace(
      `{${'reviewId'}}`,
      encodeURIComponent(String(requestParameters['reviewId']))
    );

    return {
      path: urlPath,
      method: 'PATCH',
      headers: headerParameters,
      query: queryParameters,
      body: UpdateReviewToJSON(requestParameters['updateReview']),
    };
  }

  /**
   * 리뷰를 수정합니다. 본인의 리뷰만 수정할 수 있습니다.
   * 리뷰 수정
   */
  async teamIdReviewsReviewIdPatchRaw(
    requestParameters: TeamIdReviewsReviewIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ReviewWithDetails>> {
    const requestOptions = await this.teamIdReviewsReviewIdPatchRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ReviewWithDetailsFromJSON(jsonValue)
    );
  }

  /**
   * 리뷰를 수정합니다. 본인의 리뷰만 수정할 수 있습니다.
   * 리뷰 수정
   */
  async teamIdReviewsReviewIdPatch(
    requestParameters: TeamIdReviewsReviewIdPatchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ReviewWithDetails> {
    const response = await this.teamIdReviewsReviewIdPatchRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates request options for teamIdReviewsStatisticsGet without sending the request
   */
  async teamIdReviewsStatisticsGetRequestOpts(
    requestParameters: TeamIdReviewsStatisticsGetRequest
  ): Promise<runtime.RequestOpts> {
    if (requestParameters['teamId'] == null) {
      throw new runtime.RequiredError(
        'teamId',
        'Required parameter "teamId" was null or undefined when calling teamIdReviewsStatisticsGet().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('Bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }

    let urlPath = `/{teamId}/reviews/statistics`;
    urlPath = urlPath.replace(
      `{${'teamId'}}`,
      encodeURIComponent(String(requestParameters['teamId']))
    );

    return {
      path: urlPath,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    };
  }

  /**
   * 팀 전체 리뷰 통계를 조회합니다.
   * 리뷰 전체 통계
   */
  async teamIdReviewsStatisticsGetRaw(
    requestParameters: TeamIdReviewsStatisticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ReviewStatistics>> {
    const requestOptions = await this.teamIdReviewsStatisticsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ReviewStatisticsFromJSON(jsonValue)
    );
  }

  /**
   * 팀 전체 리뷰 통계를 조회합니다.
   * 리뷰 전체 통계
   */
  async teamIdReviewsStatisticsGet(
    requestParameters: TeamIdReviewsStatisticsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ReviewStatistics> {
    const response = await this.teamIdReviewsStatisticsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 */
export const TeamIdMeetingsMeetingIdReviewsGetSortByEnum = {
  CreatedAt: 'createdAt',
  Score: 'score',
  ParticipantCount: 'participantCount',
} as const;
export type TeamIdMeetingsMeetingIdReviewsGetSortByEnum =
  (typeof TeamIdMeetingsMeetingIdReviewsGetSortByEnum)[keyof typeof TeamIdMeetingsMeetingIdReviewsGetSortByEnum];
/**
 * @export
 */
export const TeamIdMeetingsMeetingIdReviewsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdMeetingsMeetingIdReviewsGetSortOrderEnum =
  (typeof TeamIdMeetingsMeetingIdReviewsGetSortOrderEnum)[keyof typeof TeamIdMeetingsMeetingIdReviewsGetSortOrderEnum];
/**
 * @export
 */
export const TeamIdReviewsGetSortByEnum = {
  CreatedAt: 'createdAt',
  Score: 'score',
  ParticipantCount: 'participantCount',
} as const;
export type TeamIdReviewsGetSortByEnum =
  (typeof TeamIdReviewsGetSortByEnum)[keyof typeof TeamIdReviewsGetSortByEnum];
/**
 * @export
 */
export const TeamIdReviewsGetSortOrderEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const;
export type TeamIdReviewsGetSortOrderEnum =
  (typeof TeamIdReviewsGetSortOrderEnum)[keyof typeof TeamIdReviewsGetSortOrderEnum];
